### ISSUE TITLE
missing rows

### ISSUE THREAD

**Issue by kedall** [dhorions/boxable#103]
hi ,
 when i try to run this  code, it creates a document but the first 25 rows are missing. Any ideas why ? 
 
``` java	
PDPage myPage = new PDPage(PDRectangle.A4);
		PDDocument mainDocument = new PDDocument();
		try {
			PDPageContentStream contentStream = new PDPageContentStream(mainDocument, myPage);
			List<List> data = new ArrayList();
			data.add(new ArrayList<>(
					Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));

			//Dummy Table
			float margin = 50;
			// starting y position is whole page height subtracted by top and bottom margin
			float yStartNewPage = myPage.getMediaBox().getHeight() - (2 * margin);
			// we want table across whole page width (subtracted by left and right margin ofcourse)
			float tableWidth = myPage.getMediaBox().getWidth() - (2 * margin);

			boolean drawContent = true;
			float yStart = yStartNewPage;
			float bottomMargin = 70;
			// y position is your coordinate of top left corner of the table
			float yPosition = 550;

			for (int i = 1; i <= 100; i++) {
				data.add(new ArrayList<>(
						Arrays.asList("Row " + i + " Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
			}
			BaseTable dataTable = new BaseTable(550, yStartNewPage, bottomMargin, tableWidth, margin, mainDocument, myPage, true, drawContent);

			DataTable t = new DataTable(dataTable, myPage);
			t.addListToTable(data, DataTable.HASHEADER);
			dataTable.draw();

			contentStream.close();

			mainDocument.save("testfile.pdf");
			mainDocument.close();

		} catch (IOException e) {
			e.printStackTrace();
		}
```

**Comment by Frulenzo** [comment]
You need to include your first page to your document and your contentStream is here redudant.

```java
mainDocument.addPage(myPage);
``` 

Check `listTestLandscape` test case in `DataTableTest` class for more info.

**Comment by kedall** [comment]
@Frulenzo  thanks for the pointer to the test - will check it.
I added ContentStream because the wiki says that is needed.
https://github.com/dhorions/boxable/wiki (could you please tell me why its redundant or when it should not be used)?

**Comment by kedall** [comment]
@Frulenzo i used the example to make a slightly better table - but its still not cool. 
for instance 
I did this: (the 2 tables stick together - see link below and how can I get the cells of the first table to be the same width as the second table)?

basically in my example I want a bunch of tables that can span one or more pages.

`
public void export(@Valid beanFilter filter){
		List<CCHbean> beans = getbeans(Arrays.asList(filter.getbeanId()));
		
		//Initialize Document
		PDDocument doc = new PDDocument();
		PDPage page = new PDPage();
		//Create a landscape page
		page.setMediaBox(new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth()));
		doc.addPage(page);
		//Initialize table
		float margin = 10;
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		float yStart = yStartNewPage;
		float bottomMargin = 0;
		
		try {
			
			for (CCHbean bean : beans) {
				//Create the data
				List<List> data = new ArrayList();
				data.add(new ArrayList<>(Arrays.asList("bean Name", quote(bean.getbeanName()))));
				data.add(new ArrayList<>(Arrays.asList("Jurisdiction", quote(bean.getJurisdiction()))));
				data.add(new ArrayList<>(Arrays.asList("bean Category", quote(bean.getbeanCategory()))));
				data.add(new ArrayList<>(Arrays.asList("Industry", quote(bean.getIndustry()))));
				data.add(new ArrayList<>(Arrays.asList("Tax / bean Type", quote(bean.getTaxbeanType()))));
				data.add(new ArrayList<>(Arrays.asList("Geographic Consideration", quote(bean.getGeographicConsiderations()))));				
				data.add(new ArrayList<>(Arrays.asList("bean Description", quote(bean.getbeanDescription()))));
				data.add(new ArrayList<>(Arrays.asList("Amount", quote(bean.getAmount()))));

				BaseTable dataTable = null;
				dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,
	                    true);
				DataTable t = new DataTable(dataTable, page);
				t.addListToTable(data, DataTable.NOHEADER);

				yStart = dataTable.draw() + 50;				
			};
			
			File file = new File("test.pdf");

			Files.createParentDirs(file);
			doc.save(file);
			doc.close();

		} catch (IOException e) {
			e.printStackTrace();
		}		
	}
	
	private String quote(String s){
		return s.replaceAll("\uFFFD", "")
		.replaceAll("\n", "<br><br>");
	}

`

[test.pdf](https://github.com/dhorions/boxable/files/946148/test.pdf)

**Comment by Frulenzo** [comment]
@kedall 
You are right. In most cases we need our ContentStream and not in all cases. I really need to be more exact in wiki. Thanks for pointing that out :wink: 
I am really busy right now but I will try to answer you later today or tomorrow at the latest.

**Comment by Frulenzo** [comment]
@kedall 
So the first thing that I saw it's wrong is your yPosition of your second table here:
```java
yStart = dataTable.draw() + 50;				
```
+ is going up
- is going down

Secondly : 

> how can I get the cells of the first table to be the same width as the second table

For this I need to make some test cases because I didn't implement that part with dataTable but if you want to preserve the same cells width I would do something like
`csvTestSimple()` test case (pay attention on `createCell()` method where you provide cell width):

```java
//Add a few things to the table that's not coming from the csv file
        Row h1 = dataTable.createRow(0f);
        Cell c1 = h1.createCell(100, "Electricity Prices by type of user");
        c1.setFillColor(new Color(144, 195, 212));
        dataTable.addHeaderRow(h1);
        Row h2 = dataTable.createRow(0f);
        Cell c2 = h2.createCell(100, "Eur per kWh for Medium Size Households.<br/>Source <i>http://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&plugin=1&language=en&pcode=ten00117</i>");
        c2.setFillColor(new Color(175, 212, 224));
        dataTable.addHeaderRow(h2);
        DataTable t = new DataTable(dataTable, page);
        t.addCsvToTable(data, DataTable.HASHEADER, ';');
        dataTable.draw();
```

**Comment by Frulenzo** [comment]
Updated wiki && closing issue
