### ISSUE TITLE
Retrieve position with table spanning multiple pages

### ISSUE THREAD

**Issue by Erwin-t-Hoen** [dhorions/boxable#105]
When creating a table that spans multiple pages I want to add text below that table.
I start out with:
PDPageContentStream contentStream = new PDPageContentStream(doc, initialPage, AppendMode.APPEND, true);
On this initialPage the table is drawn, but this now spans 2 pages and a small part of page 3.
How do I find the position for drawing a text below the table on page 3?

**Comment by Frulenzo** [comment]
Just try to get y position where your table ends and give it more space to your text don't start exactly underneath the table. Something like:

```java 
yStart = table.draw() - 50;
PDPageContentStream textContentStream = new PDPageContentStream(doc, table.getCurrentPage(), true,
				true);
		textContentStream.beginText();
		textContentStream.setFont(PDType1Font.HELVETICA_BOLD, 22);
		textContentStream.moveTextPositionByAmount(50, yStart);
		textContentStream.drawString("Here is my text below the table");
		textContentStream.endText();
		textContentStream.close();
```
Pay close attention to second argument of PDPageContentStream, you need to provide `currentPage` and not `page` (initial page)

**Comment by Frulenzo** [comment]
Documentation updated && closing issue

**Comment by flurinBoonea** [comment]
I am currently not in the office and will reply to your email upon my return on the 2nd of May 2017.

Ich bin zur Zeit nicht im Büro und werde nach meiner Rückkehr am 2. Mai 2017 antworten.

Flurin Capaul
