### ISSUE TITLE
X coordinate

### ISSUE THREAD

**Issue by divyasreeg** [dhorions/boxable#109]
Hi Team,
I would like to start my table at position (70,700) coordinates. But by using boxable it is painting the table at around (10,y-coordinate). please let me know how to change this

**Comment by Frulenzo** [comment]
Hmm, something like :

```java
BaseTable dataTable = new BaseTable(700, yStartNewPage, bottomMargin, tableWidth, 70, mainDocument,
					myPage, true, drawContent);
```

**Comment by Frulenzo** [comment]
I assume this problem is solved

**Comment by fabiobsantos92** [comment]
@Frulenzo 
This post save me hours of search, with margin arg after with arg you can move the table on X axis.

Thank you!
