### ISSUE TITLE
Issue with pdfbox v. 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by AndrejKocen2** [dhorions/boxable#11]
Hi dhorions,

the folloving code:
BaseTable table  = new BaseTable(yStart,yStartNewPage, bottomMargin, tableWidth, margin, document, page1, true, drawContent);

produces an error:
Severe: java.lang.NoClassDefFoundError: org/apache/pdfbox/pdmodel/edit/PDPageContentStream

It seems that current version is not working with the latest version of pdfbox, or am I missing something? Do you have any plans for updating your plugin?

Here is also a part from my pom.xml:
              <dependency>
		  <groupId>org.apache.pdfbox</groupId>
		  <artifactId>pdfbox</artifactId>
		  <version>2.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
		    <groupId>com.github.dhorions</groupId>
		    <artifactId>boxable</artifactId>
		    <version>1.2</version>
		  </dependency>

Thank you for any help and best regards,
Andrej

**Comment by dhorions** [comment]
2.0.0-RC1

**Comment by THausherr** [comment]
We're at RC2 now :-)

**Comment by dhorions** [comment]
Hello,

this is now resolved.  
Two new versions were released 
[1.2.1](https://github.com/dhorions/boxable/releases/tag/1.2.1) - Contains the latest code from master branch, and is references Pdfbox 2.0.0-RC**1**
[1.2.2](https://github.com/dhorions/boxable/releases/tag/1.2.2)  - Contains the latest code from master branch, and is references Pdfbox 2.0.0-RC**3**
