### ISSUE TITLE
Table line spacing

### ISSUE THREAD

**Issue by divyasreeg** [dhorions/boxable#112]
HI Team,
How to set line spacing. Default is 1f. i want to set to 0.5f in https://github.com/dhorions/boxable/tree/master/src/main/java/be/quodlibet/boxable

**Comment by CSchemmy** [comment]
you can find a example at.
https://github.com/dhorions/boxable/tree/master/src/test/java/be/quodlibet/boxable/TableTest.java
If you use table.setLineSpacing(0.5f) the text will be owerwrite the line befor. Ist that what you wont?
[lineSpacingTest.pdf](https://github.com/dhorions/boxable/files/1109824/lineSpacingTest.pdf)

**Comment by divyasreeg** [comment]
I tried that earlier by using setLineSpacing(0.5f) but it asked me to type cast : ((Object) table).setLineSpacing(1.5f); which gives a compile time exception.
Also, when i type table. and ctrl+space it doesnt give auto suggestion of setLineSpacing() method.

I am using boxable 1.4 version jars (which means .class files)

**Comment by CSchemmy** [comment]
Im using maven and get version 1.4 from https://repo.maven.apache.org/maven2/com/github/dhorions/boxable/1.4/boxable-1.4.jar and the following code works fine.
`BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,true);
dataTable.setLineSpacing(1.5f);`

**Comment by Frulenzo** [comment]
As @CSchemmy mentioned, that should be supported
