### ISSUE TITLE
Table Layout

### ISSUE THREAD

**Issue by MasterGigi** [dhorions/boxable#113]
Would be nice if we could define a table layout before adding a list to the table with table.addListToTable();
It would be nice if we also could define which lines are visible like this:

![image](https://user-images.githubusercontent.com/377953/27724723-7da05244-5d73-11e7-9010-fc3b2031bf69.png)

Correct me if this is already supported.

**Comment by Frulenzo** [comment]
unfortunelly not supported 😞
