### ISSUE TITLE
Draw line in pdf

### ISSUE THREAD

**Issue by divyasreeg** [dhorions/boxable#114]
Hi Team,

How to draw line in pdf using boxable?

**Comment by divyasreeg** [comment]
I dont know the y position; say suppose i need to draw a line in the middle of the page. So how do i draw a line

**Comment by Frulenzo** [comment]
You can do it with PDStreamUtils.rect() method:
```java
public static void rect(final PDPageContentStream stream, final float x, final float y, final float width,
			final float height, final Color color)
```
 Here is one test case where I draw line at half page: 

```java
@Test
    public void drawLineTest() throws IOException {

        //Initialize Document
        PDDocument doc = new PDDocument();
        PDPage page = addNewPage(doc);
        PDPageContentStream cos = new PDPageContentStream(doc, page);
        PDStreamUtils.rect(cos, 0, page.getMediaBox().getHeight() / 2, page.getMediaBox().getWidth(), 1, Color.BLACK);
        cos.close();
        //Save the document
        File file = new File("target/lineTest.pdf");
        System.out.println("Sample file saved at : " + file.getAbsolutePath());
        Files.createParentDirs(file);
        doc.save(file);
        doc.close();
    }
```

[lineTest.pdf](https://github.com/dhorions/boxable/files/1124505/lineTest.pdf)

**Comment by divyasreeg** [comment]
Thanks Frulenzo, 
But if i need to draw lines randomly after some text example --
Helloworld xyz
Helloworld xyz
Helloworld xyz
Helloworld xyz
draw line()
Helloworld xyz
Helloworld xyz

**Comment by divyasreeg** [comment]
![image](https://user-images.githubusercontent.com/28944261/27863248-cae8126c-61a6-11e7-9b37-5327e9c69743.png)

**Comment by divyasreeg** [comment]
In this case, I dont know the current y value .
1)My requirement is to draw a table without border --> i did this by setting drawLines=false in BaseTable.
2) Draw lines between the text whenever i encounter some conditions. --> here i dont know the y value so i am unable to draw lines as and when needed.

**Comment by Frulenzo** [comment]
you should somehow always track your Y position because that's essential coordinate for anything to draw.

**Comment by divyasreeg** [comment]
Yes, thats the problem..
how do i track y position

**Comment by Frulenzo** [comment]
You can always use `Paragraph` class for your text and with `.getHeight()` method retrieve how big is your paragraph/text :) That should be good starting point
