### ISSUE TITLE
Document created with DataTable do not show first page

### ISSUE THREAD

**Issue by srijai** [dhorions/boxable#116]
I created pdf using DataTable. If there is only one page then the document does not open and shows error 'The file cannot be opened because it has no pages'. If there are more than one page the document opens but the first page is missing. I am using boxable:1.5-RC and pdfbox:2.0.0. I have attached the 2 documents created
[CodeValue20170801145344.pdf](https://github.com/dhorions/boxable/files/1190122/CodeValue20170801145344.pdf)
[CodeValue20170801145607.pdf](https://github.com/dhorions/boxable/files/1190123/CodeValue20170801145607.pdf)

**Comment by Frulenzo** [comment]
Can you provide the code so it's easier to reproduce your case?

**Comment by Frulenzo** [comment]
*bump*

**Comment by srijai** [comment]
[PdfView.java.txt](https://github.com/dhorions/boxable/files/1300118/PdfView.java.txt)

[DataTable.java.txt](https://github.com/dhorions/boxable/files/1300117/DataTable.java.txt)
I have attached the classes I have used.

**Comment by srijai** [comment]
[PdfView.java.txt](https://github.com/dhorions/boxable/files/1300210/PdfView.java.txt)


I removed the extra code I have written and just used DataTable given by you. Still same result. The List passed to the DataTable had 16 elements in it.
[CodeValue20170913223517.pdf](https://github.com/dhorions/boxable/files/1300206/CodeValue20170913223517.pdf)

**Comment by CSchemmy** [comment]
I have seen that in the first page is missing in your Document  _CodeValue20170801145607.pdf_
I think you have to do the following behind table.drow:
<if (dataTable.getCurrentPage() != page) 
   { page = dataTable.getCurrentPage(); }>

**Comment by srijai** [comment]
I tried the below code. Same result

PDPage page = new PDPage(new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth()));
		// Create a new font object by loading a TrueType font into the document
		// Get file from resources folder

		
		float margin = 50;
		// starting y position is whole page height subtracted by top and bottom
		// margin
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		// we want table across whole page width (subtracted by left and right
		// margin ofcourse)
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);

		boolean drawContent = true;
		float yStart = yStartNewPage;
		float bottomMargin = 70;

		BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, document, page,
				true, drawContent);
		List<List> data = new ArrayList();
		data.add(new ArrayList<>(
		               Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));
		for (int i = 1; i <= 100; i++) {
		  data.add(new ArrayList<>(
		               Arrays.asList("Row " + i + " Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
		
		}
		LOGGER.debug("In buildPdfDocument. Data List size: " + data.size());
		if (dataTable.getCurrentPage() != page) 
		   { page = dataTable.getCurrentPage(); }
		DataTable t = new DataTable(dataTable, page);
		t.addListToTable(data, DataTable.HASHEADER);
		dataTable.draw();
[sample20170913231215.pdf](https://github.com/dhorions/boxable/files/1300296/sample20170913231215.pdf)

**Comment by CSchemmy** [comment]
try
`	}
	LOGGER.debug("In buildPdfDocument. Data List size: " + data.size());
	DataTable t = new DataTable(dataTable, page);
	t.addListToTable(data, DataTable.HASHEADER);
	dataTable.draw();
	page = dataTable.getCurrentPage();
`

**Comment by srijai** [comment]
Same result. First page missing. 

float margin = 50;
		// starting y position is whole page height subtracted by top and bottom
		// margin
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		// we want table across whole page width (subtracted by left and right
		// margin ofcourse)
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);

		boolean drawContent = true;
		float yStart = yStartNewPage;
		float bottomMargin = 70;

		BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, document, page,
				true, drawContent);
		List<List> data = new ArrayList();
		data.add(new ArrayList<>(
		               Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));
		for (int i = 1; i <= 100; i++) {
		  data.add(new ArrayList<>(
		               Arrays.asList("Row " + i + " Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
		
		}
		LOGGER.debug("In buildPdfDocument. Data List size: " + data.size()); 
		DataTable t = new DataTable(dataTable, page); 
		t.addListToTable(data, DataTable.HASHEADER); 
		dataTable.draw(); 
		page = dataTable.getCurrentPage();
[sample20170913232514.pdf](https://github.com/dhorions/boxable/files/1300320/sample20170913232514.pdf)

**Comment by CSchemmy** [comment]
I'm using the follow and it works
    <groupId>com.github.dhorions</groupId>
    <artifactId>boxable</artifactId>
    <version>1.4.0</version>
please try

**Comment by srijai** [comment]
I tried. There are no errors in my server side logs. But the first page is missing even with the simple example code given here. I am using spring MVC and saving the document to a ByteArrayOutputStream. Is there any problem because of this?

                ByteArrayOutputStream baos = createTemporaryOutputStream();
		PDDocument document = new PDDocument();
		buildPdfDocument(model, document, request, response);
		document.save(new BufferedOutputStream(baos));
		document.close();
		writeToResponse(response, baos);

**Comment by srijai** [comment]
Solved the issue. I had not added the page to the document after creating it. Once I added the below line after creating the page it works fine. Thanks for your help.

document.addPage(page);

**Comment by CSchemmy** [comment]
you can Clone my repsetory []( https://github.com/CSchemmy/boxable)
after clone you must change the follow part from **verify** to **deploy**
```
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                  <execution>
                    <id>sign-artifacts</id>
                    <phase>deploy</phase>
                    <goals>
                      <goal>sign</goal>
                    </goals>
                  </execution>
                </executions>
              </plugin>

```
and than a `maven install ` after that you can use version 1.4.1
