### ISSUE TITLE
Content goes to next page

### ISSUE THREAD

**Issue by karimaelo** [dhorions/boxable#117]
I would like to know if the content in the table keeps going to the next page. 
How to handle that? 
Is there a way to handle the current position? 
What is the best practice when dealing with such scenarios?
Are you going to release the fond coloring layout change soon?

**Comment by dhorions** [comment]
Tables will go to the next pages if not all rows fit.
The header rows will be repeated on all pages.
You can use table.getCurrentPage() after .draw() to get the page where the table ended.
