### ISSUE TITLE
ContentStream positions text wrong when Table is longer than a single page

### ISSUE THREAD

**Issue by racebennon** [dhorions/boxable#121]
Hi, 
Okay title might not be a very good one, hard to know how to summarise the situation. Hopefully I'll make more sense here. Okay so this is in reference to my previous question (Ref: https://github.com/dhorions/boxable/issues/119).
The issue is that I am using the following code to generate contentStream, 

> PDPageContentStream contentStream = new PDPageContentStream(doc, page, AppendMode.APPEND, true);

When setting the position I use the following, 

> contentStream.moveTextPositionByAmount(margin + 5, yPos - 20);

where **float yPos = table.draw()** and **margin = 50**
Now when I generate a PDF with table that stretches to 2 pages, Instead of content displaying after the end of table on Page 2, it displays the content on the first page behind the table. 

Any help! Or if anyone else has gone through the same ... please help

**Comment by CSchemmy** [comment]
I think you have to do the following behind table.drow:
`        if (dataTable.getCurrentPage() != page) {
            page = dataTable.getCurrentPage();
        }
`

**Comment by CSchemmy** [comment]
You can find an example at my repositorie CSchemmy:master 
src/test/java/be/quodlibet/boxable/DataTableTest.java -> public void csvTestAdvanced().
There I generate some tables in one PDF
See pull request #110

**Comment by racebennon** [comment]
@CSchemmy ... Thanks a lot! Worked like a charm! So this is what I did, after drawing the table, 

> float yPos = table.draw()

Before creating contentStream, I used your code, 

> if (table.getCurrentPage() != page) { 

>          page  = table.getCurrentPage();

>  }

And it worked amazing 

Thanks
