### ISSUE TITLE
Table border problem when using fillColor on Acrobat Pro DC(IE or acrobat 9 works fine)

### ISSUE THREAD

**Issue by iti888** [dhorions/boxable#123]
Hi,
I am using boxable to create a PDF table. It looks fine if I open it with Browser or Acrobat 9.
But if I use the newest acrobat Pro DC., then the fillColor cell (I have alternate color schema on table). Then border display or not is not controllable.
Anyone has any idea? Looks like fillColor is overlaying the border, and render it invisible.
The attached file is the sample report. If you open it with browse or older version of Acrobat, it works just fine. But if you use the latest Acrobat Pro DC, then the border is not controllable.
Thanks
[boxale_report.pdf](https://github.com/dhorions/boxable/files/1338802/boxale_report.pdf)

**Comment by iti888** [comment]
Never mind. It is just a preference setting in Pro DC that I need to unset (Enhance thin lines under Page Display)

**Comment by marcodelella** [comment]
hi, I have same problem, have u resolved?

**Comment by iti888** [comment]
DC setting issue. 

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 3, 2020 at 1:02 AM, marcodelella<notifications@github.com> wrote:   


hi, I have same problem, have u resolved?

**Comment by marcodelella** [comment]
Hi,
I am using boxable and I have the following problem:
when I use setFillColor, in the last column in the row the color overflows
outside the table border. There is a way to solve?
https://github.com/dhorions/boxable/issues/174

Il giorno mer 3 giu 2020 alle ore 17:39 Hong Bai <notifications@github.com>
ha scritto:

**Comment by mailidpankaj** [comment]
Hi,

I am using setFillColor to fill the table cell. The color overflows from the last table cell. Please let me know how can I fix this issue.
Thanks.

Regards,
Pankaj
