### ISSUE TITLE
StackOverflowError when drawing a table over multiple pages

### ISSUE THREAD

**Issue by AndresManuel1** [dhorions/boxable#124]
I am creating my table like this:

`BaseTable table = new BaseTable(y, 0, 30, 30, 100, 30, doc, page, true, true);`

Add a simple header row then add some more content rows. 
I think I found the issue in your code already. Check out your Table#drawRow method

    if (isEndOfPage(row)) {
        endTable();
        pageBreak();
        // redraw all headers on each currentPage
        if (!header.isEmpty()) {
            for (Row<T> headerRow : header) {
                drawRow(headerRow); // <-- THIS RECURSIVE CALL
            }
		removeTopBorders = true;
        } else {
		removeTopBorders = false;
        }
    }

On a new page you want to draw your header again, the problem is you are never resetting your variable 'startingY'. The methods endTable() and pageBreak() just create a new page & stream and close the old stream. The result of isEndOfPage(row) is ALWAYS true once you reach the bottom of your first page.

**Comment by AndresManuel1** [comment]
hello? can you help with this?

**Comment by dhorions** [comment]
If you don't want the headers to be repeated, try creating a normal row and
format it as a header on the first page only.


http://quodlibet.be

**Comment by AndresManuel1** [comment]
I do want the headers repeated, there is just an error in the code...

**Comment by dhorions** [comment]
I just ran unit test [SampleTest4](https://github.com/dhorions/boxable/blob/master/src/test/java/be/quodlibet/boxable/TableTest.java#L377) and that produces the expected output. 
Sample attached.
[BoxableSample4.pdf](https://github.com/dhorions/boxable/files/1686108/BoxableSample4.pdf)

So I'm not able to reproduce the issue based on the information you have given.
Please provide a complete code sample and example output.
