### ISSUE TITLE
Adding images to the table instead of data

### ISSUE THREAD

**Issue by Suryaphaneeth** [dhorions/boxable#126]
I was trying to add images in the Basetable object. It is throwing some errors. I am not sure whether it is possible or not. If it is possible in some way can you please let me know. 

https://mvnrepository.com/artifact/com.github.dhorions/boxable

I am adding maven dependencies from this link. 

I appreciate your help.

Thank you

**Comment by Frulenzo** [comment]
Hmm, can you say which erros, show test case or PDF?

If you want image inside your table cell you can write something like 

```java
cell = row.createImageCell(cellWidth, ImageUtils.readImage(imageFile));
```
