### ISSUE TITLE
Lengthy text is all jumbled up when displayed in the table cell

### ISSUE THREAD

**Issue by MMPdf** [dhorions/boxable#127]
The text is all jumbled if it is lengthy. It is a normal String field.

**Comment by Frulenzo** [comment]
Can you be more specific? PDF, test example? 

I can only tell you that text output is determined by table cell width. If you text length > table cell width, it will be sliced by last letter that can be fitted in first row and then continued in the next row.

**Comment by tvirtualw** [comment]
Not sure if he refers to the same issue but we've seen the following problem:
We take a longer text (for example first paragraph of a Lorem Ipsum text) and add it to a table cell. At the end of the cell, the lines are not in order.

After debugging, it seems the problem may be in `for (Map.Entry<Integer, List<Token>> entry : cell.getParagraph().getMapLineTokens().entrySet()) {` of `be.quodlibet.boxable.Table#drawCellContent`.

It uses `be.quodlibet.boxable.Paragraph#mapLineTokens` which is a HashMap. The keys in the HashMap are not sorted (no guarantee for order).

The keys in `mapLineTokens` in our debugged example are: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 16, 19, 18, 20. After 15, the remaining lines are in the wrong order.

I don't know much about the project but it seems you may want to use a LinkedHashMap there instead which guarantees order or some other way to ensure iteration happens in proper order.

**Comment by Frulenzo** [comment]
Hmmm, isn't that this commit -> [https://github.com/dhorions/boxable/commit/29d73812478b6bea59f3a24e33e18ddc3b554e87](url)

**Comment by tvirtualw** [comment]
Yes, that's the fix. But it doesn't seem to be available in the latest release shown on the main page (1.4).
Would be good to get a new release then.

I've checked http://mvnrepository.com/artifact/com.github.dhorions/boxable and it seems there is a 1.5 RC available. I assume the fix is in there. Is it production ready?

**Comment by dhorions** [comment]
To use the current master branch with maven you can use jitpack.

 ```xml
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```
```xml
<dependencies>
    <dependency>
	    <groupId>com.github.dhorions</groupId>
	    <artifactId>boxable</artifactId>
	    <version>master</version>
	</dependency>
</dependencies>
```

I'm hoping to find some time soon to release a new version.
