### ISSUE TITLE
Infinite recursion when yStartNewPage is too small

### ISSUE THREAD

**Issue by Heeten** [dhorions/boxable#13]
This is mostly user error, if yStartNewPage is small enough that the row being added to a new page ends up causing isEndOfPage() to be true when adding the header you end up with an infinite recursion at line 184 of Table.java

**Comment by dhorions** [comment]
Hi,

would you mind testing this with the latest committed changed and letting me know if this issue still exists?

Dries

**Comment by dhorions** [comment]
Closing issue due to lack of response.  Please let me know if it needs to be re-opened.
