### ISSUE TITLE
How to create multiple tables in single pdf

### ISSUE THREAD

**Issue by mirzaaqib** [dhorions/boxable#132]
I am using boxable library for generating the pdf. I want to add many tables in my pdf report. I am getting error.Can you please provide me the code or any help how i can do that.

Thank You!

**Comment by CSchemmy** [comment]
In my fork you can find an example in the test
boxable/src/test/java/be/quodlibet/boxable/DataTableTest.java
csvTestAdvanced().

**Comment by dhorions** [comment]
@CSchemmy 's [example](https://github.com/CSchemmy/boxable/blob/master/src/test/java/be/quodlibet/boxable/DataTableTest.java#L241) should help you along :

**Comment by VarunSantosh** [comment]
Hi ,

How can I create multiple tables one after another in one page?

**Comment by yahmed-mohammad** [comment]
Hi,
How can I create multiple tables one after another in one page? - I was able to create two tables but the second table is starting from the same place(middle of the page) for next pages as well.

Can anyone help me on this?
