### ISSUE TITLE
First page at bottom in multipage table

### ISSUE THREAD

**Issue by patryksosinski** [dhorions/boxable#133]
I am trying to follow tutorial at viki and i am stuck with multi page tables. It seems that second page is generated above the first and then it goes normally. So with 3 pages the pages are 2, 3, 1. See attached pdf sample where title is on the last page.
[longReport.pdf](https://github.com/dhorions/boxable/files/1476472/longReport.pdf)

Here is my code:

`public class PdfCreator {

	/**
	 * Default page margin
	 */
	private static final float MARGIN = 50;
	/**
	 * Line size between elements
	 */
	private static final float BR = 10;
	
	private static final float ROW_HEIGHT = 15;
	
	private static final PDFont FONT = PDType1Font.HELVETICA;
	
	private PDPage page = null;
	private PDDocument doc = null;
	
	private File outputFile;
	
	public PdfCreator(File file) {
		this.outputFile = file;
	}
	
	private void initDocument() {
		page = new PDPage(PDRectangle.A4);
		doc = new PDDocument();
	}
	
	public void createTableReport(String title, List<List<String>> data) throws IOException {
		
		initDocument();
		PDPageContentStream contentStream = new PDPageContentStream(doc, page);
		
		//starting y is page height - top and bottom margins
		float height = page.getMediaBox().getHeight() - (2 * MARGIN); 
		float y = page.getMediaBox().getHeight() - MARGIN;
		
		writeTitle(contentStream, title, y);
		y -= BR*2;
		
		float width = page.getMediaBox().getWidth() - (2 * MARGIN);
		boolean drawContent = true;
		
		BaseTable table = new BaseTable(y, height, MARGIN, width, MARGIN, doc, page, true, drawContent);
		
		createHeader(table);
		
		for (List<String> dataRow : data ) {
			Row<PDPage> row = table.createRow(12);
			boolean first = true;
			for (String column : dataRow) {
				if (first) {
					Cell<PDPage> cell = row.createCell(34, column);
					first = false;
				}else{
					Cell<PDPage> cell = row.createCell(33, column);
				}
				
			}
		}

	    table.draw();

	    contentStream.close();
	    doc.addPage(page);
	    doc.save(outputFile);
	    doc.close();
	}
	
	private void createHeader(BaseTable table) {
		Row<PDPage> headerRow = table.createRow(ROW_HEIGHT);
		Cell<PDPage> c1 = headerRow.createCell(34, "User");
		Cell<PDPage> c2 = headerRow.createCell(33, "Privileges");
		Cell<PDPage> c3 = headerRow.createCell(33, "Derived");
		c1.setFillColor(Color.LIGHT_GRAY);
		//c1.setFont(PDType1Font.COURIER);
		c2.setFillColor(Color.LIGHT_GRAY);
		c3.setFillColor(Color.LIGHT_GRAY);
		//c2.setFont(PDType1Font.COURIER);
		table.addHeaderRow(headerRow);
	}
	
	private void writeTitle(PDPageContentStream cos, String title, float y) {
		PDStreamUtils.write(cos, title, FONT, 14, MARGIN, y,
                Color.BLACK);
	}`

**Comment by patryksosinski** [comment]
If I addPage before drawing table everything seems ok:

`doc.addPage(page);
dataTable.draw();`

In examples adding page is after drawing:

`table.draw();
    contentStream.close();
    mainDocument.addPage(myPage);
    mainDocument.save("testfile.pdf");`

**Comment by CSchemmy** [comment]
In my fork you can find an example in the test
 boxable/src/test/java/be/quodlibet/boxable/DataTableTest.java
csvTestAdvanced().
If the table is longer than one page, it must be set new before you want to write more stuff in the document.
`        if (table.getCurrentPage() != page) {
            page = table.getCurrentPage();
        }
`

**Comment by dhorions** [comment]
Exactly, when starting a new table, the page you pass to it will be the page where the table starts.

**Comment by jonathanmza** [comment]
`if (table.getCurrentPage() != page) { page = table.getCurrentPage(); }` doesn't fix the issue.

The problem is here : 

```
table.draw();

contentStream.close();
doc.addPage(page);
doc.save(outputFile);
doc.close();
```
You start drawing before adding the page.

The right way to do it :

```
contentStream.close();
doc.addPage(page);
table.draw();
doc.save(outputFile);
doc.close();
```
It works for me.
