### ISSUE TITLE
table header row again gets added as new page starts

### ISSUE THREAD

**Issue by abhijitatmaram** [dhorions/boxable#136]
Hi there,
i am working with boxable to generate PDF . but as attached in image table header row again gets added on new page. How can we prevent that too happen. I do not want  header row again to be addded.
![pdfissues](https://user-images.githubusercontent.com/24814150/33771763-4d5f581e-dc58-11e7-9ee2-6597175dcd50.JPG)

**Comment by dhorions** [comment]
A header row will always get repeated on each page if not all rows of your table fit on one page.   That in fact is the only thing that makes a header row  special.
If you don't want that, don't use a header row and just use 'normal' rows.
