### ISSUE TITLE
Get all the pages a single table is drawn on and also the page a row belongs to.

### ISSUE THREAD

**Issue by bhchandra** [dhorions/boxable#137]
A table can contain a huge data set and occupies many pages.

Is there a way to get all the pages the table is drawn on? 

`List<PDPage> allPages = table.getPages();`

and also,

the page  each Row belongs to?

`PDPage page = row.getPage();`

Edit: 

The reason this is required is: I would like to add navigation links to the tables.
This would provide good experience to the user browsing big tables.

Currently, It is possible to track the (x,y) co-ordinates of a Table, row and cell. The only missing information is the *page* a *row* belongs to.

If page information is available, it is possible to draw annotations on the Tables.

**Comment by dhorions** [comment]
[This example ](https://github.com/dhorions/boxable/blob/master/src/test/java/be/quodlibet/boxable/TableTest.java#L377) uses bookmarks, perhaps that will help you. 

To get all the pages of a table, you can do something like this : 
When you create a table, you pass the first page to it.

```java
BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, startPage, true, drawContent);`
```
the  when you finally draw it, you can get the page where the table ended : 
```java
table.draw();
PDPage lastPage = table.getCurrentPage();
```
Then you can loop through all pages between start and end of the table like this

```java
for(int p = doc.getPages().indexOf(startPage); p<=doc.getPages().indexOf(lastPage);p++)
{
  PDPage page = doc.getPages().get(p);
}
```

I didn't test this code, but think it should work.

**Comment by bhchandra** [comment]
Thank you.
I realized later that I needed more granular information such as which page each row is located.
So, I forked the project and modified some code.
It all works now and I am even done with the pdf project too.

Appreciate a lot for the library.

**Comment by dhorions** [comment]
Can you put a link in here to your solution?  Maybe it's useful and can be
added to the library.

Thanks,

Dries

http://quodlibet.be

**Comment by bhchandra** [comment]
1. Add two attributes to Row class and it's corresponding setters.
       a. PDPage `page`.(page each row belongs to).

      b. float `yStart` ( location of the row in it's page).

      Note: Do not add these fields to the constructor of Row as these attributes cannot be determined during the object creation.

2. Find the correct place call the setter methods.
    a. Add `row.setYStart(ystart)` at the end of method `Table#drawCellContent(Row<T> row)` just after the statement `yStart = yStart - row.getHeight();`.

     b. Add ` row.setPage(this.currentPage)` at the end of the method `Table#drawRow(Row<T> row)`.


You now have the required information to do your required work. (I needed this to draw annotationlinks to add navigation on large tables) :

```
   
        for (Row<PDPage> row : baseTable.getRows()) {
            if (row.isHeaderRow()) {
                continue;//ignore headers
            }
           //do work
        }

```
