### ISSUE TITLE
Setting of Linespacing not working

### ISSUE THREAD

**Issue by Nishi-Fertig-Aus** [dhorions/boxable#139]
The 1.4 version downloadable via Maven has no public setLineSpacing() method in BaseTable. So I imported the 1.5-RC version from Maven. Even though this version provides this methdod for BaseTable objects, no PDF is created if the Linespacing is set with a value different than 1.0f due to an Error. No Error message is output.

**Comment by Nishi-Fertig-Aus** [comment]
The PDF is created, even if I set LineSpacing to 1.0f.

**Comment by Frulenzo** [comment]
Are you sure? Did you try to run lineSpacingTest() in TableTest class? That's JUnit test exactly for what you are askin' for.

Here is my pdf output from this test case
[lineSpacingTest.pdf](https://github.com/dhorions/boxable/files/1622833/lineSpacingTest.pdf)

**Comment by Nishi-Fertig-Aus** [comment]
Thank your Frulenzo. I was wrong and your code works. I made the mistake, that I had loaded the 1.5-RC version in the first Class loader and hided it again with the 1.4 version that I forgot to remove from the second class loader. After removing your 1.4 version from the second class loader everything works just fine. Thank you.
