### ISSUE TITLE
Drawing text other than tables

### ISSUE THREAD

**Issue by sponde210** [dhorions/boxable#14]
It is possible to get a reference to the PDPageContentStream that boxable uses so that I can write other text to the PDF (besides tables) and call moveTextPositionByAmount() to move around the page? I made a getter method to retrieve tableContentStream from within BaseTable and tried calling moveTextPositionByAmount() on that, but it does not seem to work.

**Comment by Kravs** [comment]
I did that by drawing 1x1 table without borders.
Not perfect solution, but I used it only to draw titles ...so in some cases it might work.

**Comment by Frulenzo** [comment]
With the current code there are two ways:
1. If you just want to add a title to a table, you can call one of the ```table.drawTitle()``` methods.
2. If you want to draw text anywhere, you have to use a separate ```PDPageContentStream```. You can use ```be.quodlibet.boxable.utils.PDStreamUtils```:

```java
PDPageContentStream stream = new PDPageContentStream(document, page);
PDStreamUtils.write(stream, text, font, fontSize, posX, posY, color);
```

**Comment by Frulenzo** [comment]
@dhorions I think this issue is already solved

**Comment by dhorions** [comment]
You are welcome, closing issue.
