### ISSUE TITLE
Missing Borders

### ISSUE THREAD

**Issue by mcory** [dhorions/boxable#140]
Hi,
    Thank you for the boxable project.
    While trying to create a pdf with my data in a table I find that some cell borders are missing.
    To trouble shoot the issue I created a new Java project and included only the code from a boxable  sample class.
    Even with just the code from the boxable sample, I find some borders are missing from the table.
 
    I am using boxable-1.5-RC1 and PDFBox-2.0.7
    I have tried with PdfBox-2.0.0 using JDK 1.8 and JDK 1.7
 
    I realize that boxable-1.5-RC1 is only a release candidate, but I think this is the first release to include classes such as DataTable?

    Here is the code I am using to test...

	public void testPdf() throws Exception {
		try {
	        //Initialize Document
	        PDDocument doc = new PDDocument();
	        PDPage page = new PDPage();
	        
	        //Create a landscape page
	        page.setMediaBox(new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth()));
	        doc.addPage(page);
	        
	        //Initialize table
	        float margin = 10;
	        float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
	        float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
	        float yStart = yStartNewPage;
	        float bottomMargin = 0;
			
	        //Create the data
	        List<List> data = new ArrayList();
	        data.add(new ArrayList<>(
	                Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));
	        for (int i = 1; i <= 100; i++) {
	            data.add(new ArrayList<>(
	                    Arrays.asList("Row " + i + " Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
	        }

	        BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true, true);
	        DataTable t = new DataTable(dataTable, page);
	        t.addListToTable(data, DataTable.HASHEADER);
	        dataTable.draw();
	        
	        File file = new File("d:/temp/boxable/test.pdf");
	        System.out.println("Sample file saved at : " + file.getAbsolutePath());
	        Files.createParentDirs(file);
	        doc.save(file);
	        doc.close();
		} catch (Exception ex) {
			ex.printStackTrace();
			throw ex;
		} 
	}

And here is a screen capture of the resulting pdf,,,

![image](https://user-images.githubusercontent.com/22060025/35053922-765c858a-fb79-11e7-8718-e464e87f9a8a.png)

Finally I attached the resulting pdf file. Does anyone not see the missing borders in this pdf?

Not sure what I am doing wrong, but any help would be appreciated.
Thank You.
[test.pdf](https://github.com/dhorions/boxable/files/1639758/test.pdf)

**Comment by dhorions** [comment]
Hi @mcory ,
Looking at the pdf, I can see all the borders just fine.
What sometimes happens, depending on the pdf reader you use, is that when you are zoomed out, thin lines don't get rendered on the screen.  Can you try zooming in and see if you can see the borders then?  


Thanks,

Dries

**Comment by mcory** [comment]
Hi Dries,
                Thank you. This never occurred to me.
                When I zoom in or print the pdf all the borders appear.

                Now my concern is that the user of my web application will have the same experience I had.
                At 100% zoom, using the latest version of Adobe Acrobat Reader it looks like some borders are missing.

                I wonder why some appear and some do not.
                Maybe I need to increase the width of the border to ensure that always show up?

Thank you.

Michael

**Comment by mcory** [comment]
Thanks Dries.
                The problem is that when my QA person (and the customer) views the pdf using the
latest version of Adobe Acrobat Reader, at 100% zoom, they expect to see the borders.

                I could understand if the problem was seen at something other than 100% zoom.

                I Googled and found others had a similar problem when converting a Word document to PDF.
                In that case there was some king of margin in the cells that obscured the border under some zoom levels.

               Is there anything like this in the PDFBox or boxable that may be causing the borders to be obscured?
                Any other work around you can think of?

Thank You.
Michael

**Comment by mcory** [comment]
I went back to calling methods on BaseTable like…

row = table.createRow(12f);
cell = row.createCell(cellWidths[0], tmName);

…instead of using DataTable and it seems to be fine.

**Comment by dhorions** [comment]
What if you just create a slightly thicker border?

```
BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true, true);
        DataTable t = new DataTable(dataTable, page);
        //Customize cell templates - Make line a little thicker
        LineStyle customline = new LineStyle(Color.BLACK, 1f);
        t.getDataCellTemplateEven().setBorderStyle(customline);
        t.getDataCellTemplateOdd().setBorderStyle(customline);

        t.addListToTable(data, DataTable.HASHEADER);
        dataTable.draw();
```

**Comment by mcory** [comment]
Dries,

                That works too. Thank you.  Going forward I am sure I will need to use the DataTable class.

                I looked at the source code yesterday but did not discover how to do this.

                I need to find the time to examine all the source and try to learn more about these libraries.

                Thanks again – PDFBox and Boxable are great!

Michael
