### ISSUE TITLE
Two tables across the same multiple pages

### ISSUE THREAD

**Issue by mrc1ark** [dhorions/boxable#141]
I'm trying to create two tables on the same page that will both span multiple pages.  

I'm following the example here: https://github.com/dhorions/boxable/wiki#how-to-get-two-tables-with-same-y-position

This works for the first page but then each table makes their own new pages instead of both tables appearing on the same pages.  For example page 1 has both table 1 and 2 but page 2, 3, and 4 have only the rest of table1 and then pages 5,6, and 7 have the rest of table2.

**Comment by mrc1ark** [comment]
I was able to correct this by using a page provider and moving the previous page back to the page where both tables were started after drawing the first table to create its extra pages.

**Comment by Frulenzo** [comment]
I'm closing this issue due inactivity. If the author has the problem still, please open a new issue with test case
