### ISSUE TITLE
Hi. I have a question. About this library.

### ISSUE THREAD

**Issue by phpbae** [dhorions/boxable#146]
Hi!
Thanks so much for creating a feature that is not supported by pdfBox!

Well.
My question is, in this example, I checked to create a PDF.
By the way, is UTF8 not supported? If it is not English, I get an error! I would be very grateful if you could help!

error log : 
java.lang.IllegalArgumentException: U+C548 ('.notdef') is not available in this font Helvetica-Bold encoding: WinAnsiEncoding

example code

float margin = 10;
            float tableWidth = pdPage.getMediaBox().getWidth() - (2 * margin);
            float yStartNewPage = pdPage.getMediaBox().getHeight() - (2 * margin);
            float yStart = yStartNewPage;
            float bottomMargin = 20;

            List<List> data = new ArrayList();
            data.add(new ArrayList<>(Arrays.asList("Column One", "Column Two", "안녕하세요", "phpbae", "no hangul")));
            for (int i = 0; i < members.size(); i++) {
                data.add(new ArrayList<>(Arrays.asList(" Col One", "tid : " + members.get(i).getTid(), "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
                BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, document, pdPage, true, true);
                DataTable t = new DataTable(dataTable, pdPage);
                t.addListToTable(data, DataTable.HASHEADER);
                dataTable.draw();
            }

            document.save(pdfFile);
            document.close();

**Comment by bhchandra** [comment]
This has nothing to do with boxable. 

I have had similar errors before when I was working with apache PDFBox.

The reason this is coming is because the font `Helvetica-Bold` provided by PDFBox does not support the character encoding.

What you need to do is load a another font which supports your required character encoding : 

`PDType0Font load(PDDocument doc, File file)`

**Comment by Frulenzo** [comment]
@bhchandra is completly right !

For this reason you can use FreeSans as default font with: `FontUtils.setSansFontsAsDefault(PDDOcument document)` method

**Comment by bhchandra** [comment]
@Frulenzo 
> For this reason you can use FreeSans as default font with: FontUtils.setSansFontsAsDefault(PDDOcument document) method

I didn't know about this method, thanks.

What I did in my fork was add another overloaded constructor, for DataTable which takes in font arguments.

`DataTable(Table table, PDPage page, PDFont bodyFont, PDFont headerFont)`

**Comment by Frulenzo** [comment]
Don't forget that for your font you need bold, italic and bold+italic version !! Because of using designated HTML tags (`<b>, <i>` etc..)

**Comment by bhchandra** [comment]
Thank you for the tip!

For now, I am only using normal and bold fonts.
