### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MasterGigi** [dhorions/boxable#148]
Hello,

I get an ArrayIndexOutOfBoundsException when trying to insert data into table with addListToTable().

Here is the Exception:

> Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:81)
at be.quodlibet.boxable.datatable.DataTable.addCsvToTable(DataTable.java:290)
at be.quodlibet.boxable.datatable.DataTable.addListToTable(DataTable.java:204)

Does anyone know how to fix this?

**Comment by Frulenzo** [comment]
Do you have code snippet so I can reproduce that easily?

**Comment by MasterGigi** [comment]
Sorry I noticed it was a problem with my List given as parameter to the function.
Another question:
I am trying to do a borderless table with table.removeAllBorders. Somehow this is not working when creating my table with addListToTable() but working when adding rows and cells by myself. 

Regards
