### ISSUE TITLE
Create table with fillable cells

### ISSUE THREAD

**Issue by reddevilserbia** [dhorions/boxable#159]
Hi,

Is there a way to create table that would contain inputs that could be filled in by user in resulting pdf? I tried to find a way to place input as cell content, but found no solution.

**Comment by luislope** [comment]
[pdf.zip](https://github.com/dhorions/boxable/files/2180349/pdf.zip)
Most important class are: PdfTest.java and ReadPdfForm.java
I hope it can help you

**Comment by reddevilserbia** [comment]
Thank you so much, if I manage to do what I have planned I will let you
know!
