### ISSUE TITLE
Table with merged rows/cells

### ISSUE THREAD

**Issue by sanketmeghani** [dhorions/boxable#163]
Is there a way to render rows within a cell? I want to create an un-even row/column structure which can be achieved in Excel by merging cells. For example, I would like to create a table which looks something like:

<img width="472" alt="screen shot 2018-08-30 at 12 32 49 am" src="https://user-images.githubusercontent.com/7963375/44809431-4bf85e80-abec-11e8-84d2-b8b52b9b4a0b.png">

Is it possible to do this?

**Comment by dhorions** [comment]
Have a look at [this](https://github.com/dhorions/boxable/blob/d654416384b33f7d0ae84f92b327aafdeda1dc09/src/test/java/be/quodlibet/boxable/TableTest.java#L211) example.  This allows merging cells within a row.

**Comment by nkshrma** [comment]
not satisfied

**Comment by nkshrma** [comment]
not satisfied
