### ISSUE TITLE
getting Cell XY coordinates

### ISSUE THREAD

**Issue by dcosio** [dhorions/boxable#176]
Im using boxable to create a table of contents(customer requirement to be in a table).. The only difficulty Im having is adding a link.. I don't see a way to do this with the Cell object so I was thinking I could just create create a rectangle using the cells xy coordinates and add it to an annotation link. There isn't any way to get this information from the Cell.. I'm attempting to getting it using the start position of the table then using the width/hight of rows/cells to derive it.. It would be create if there were 1. a way to add a link to the cell or 2.. get the coordinates of the cell.

I'm pretty new to pdfbox so, if there is a way to do this that I'm seem to not be finding.. let me know..

Regards

**Comment by dcosio** [comment]
Im closing this.. I got it working using the table data to calculate my coordinates

**Comment by idarshandalwadi** [comment]
hi @dcosio  Can you help me with the code snippet, I'm stuck with the same problem. 
Having a table and I want to give link to each cell of the table, so how can I give that?
Thanks in advance.

**Comment by dcosio** [comment]
ok. so this was from 3 yrs ago.. I did find the code. below is how i added the annotation links.. the tocRecords is just  a list of my own pojo that contains data for the Table of contents.. the rest is pdfbox

` //now that the document has all the pages we need to create annotation links for page navigation

		        	float headerHeight = table.getHeader().getHeight();
		            int currentTOCPage = -1;
		            int currentRowNumber = 0;          
	
		            float pageUpperRightY =0;
		            float lowerLeftX=  0;
		            float upperRightX = 0;
		            float lowerLeftY = 0;
				    float upperRightY = 0;
				    float rowWidth = table.getRows().get(1).getWidth();//get the width of a row(header is at index 0, we want the row since it's height will be different)
			        float rowHeight= table.getRows().get(1).getHeight();//get the last cell height(header is at index 0, we want the row)
			        float lastCellWidth = table.getRows().get(1).getCells().get(3).getWidth();//get the last cell width(header is at index 0, we want the row)
				    PDPage TOCPage  = null;
				    
				    
				     // tocRecords are just the toc records for the rows in the TOC not including the header.. The header is treated a a row in the tables and is at index 0 of tables.getRows()..
				     // so I i could use the for loop index i to manages the rows but I use a seperate variable currentRowNumber
				     
			        for(int i = 0 ; i < tocRecords.size(); i++)
			    	{
			        	
			
				            
				            
				            logger.info("Base Row width["+ rowWidth +"] lastCell width/height[" + lastCellWidth +","+ rowHeight + "] headerheight: " + headerHeight);
			        	
			        	//if we reach the max row per page then update toc page number
			        	 if( (currentRowNumber % MAX_ROWS_PER_PAGE) == 0)
			        	 {
			        		 	currentTOCPage++;
			        		 	currentRowNumber =1;//reset row count

						        
					        	TOCPage =  document.getPage(currentTOCPage);
					        	logger.info("Page upperRightY: " + TOCPage.getMediaBox().getUpperRightY());
			        	        pageUpperRightY = TOCPage.getMediaBox().getUpperRightY();

			        	        lowerLeftX= rowWidth+table.getMargin() -lastCellWidth;	
			        	        upperRightX = lowerLeftX + lastCellWidth;
			        	        
			        	        lowerLeftY = pageUpperRightY- ( (topMargin+table.getMargin()) + (currentRowNumber + rowHeight) + headerHeight);
			        	        if(currentTOCPage > 0)//for some reason the next pages after index zero need additional margin space to find the first row.. don't know if this will continue to push down with each TOC poge
			        	        	lowerLeftY = lowerLeftY - topMargin;
							    upperRightY = lowerLeftY + (rowHeight);

					        	
			        	 }
			        	 else
			        	 {
			        		 //if we are not at a new page then we only need to add the rowHeight to the upper and lower Y coordinates for the next annotation rectangle
			        		 lowerLeftY = lowerLeftY - (rowHeight);
							 upperRightY = upperRightY - (rowHeight);
							 currentRowNumber++;
			        	 }
					       
			        
			        
			        	TableOfContentsRecord tocRec = tocRecords.get(i);
			
			        	
			           	
				        
				        logger.info("Row: " + i + " LowerLeftXY[" + lowerLeftX +"," + lowerLeftY + "] upperRightXY[" + upperRightX + "," + upperRightY +"]");
				        PDAnnotationLink annotationLink = new PDAnnotationLink();
				        PDRectangle position = new PDRectangle();
				        position.setLowerLeftX(lowerLeftX);
				        position.setLowerLeftY(lowerLeftY);
				        position.setUpperRightX(upperRightX);
				        position.setUpperRightY(upperRightY);
				        PDBorderStyleDictionary border = new PDBorderStyleDictionary();
				        border.setStyle(PDBorderStyleDictionary.STYLE_UNDERLINE);
				        border.setWidth(0);
				        annotationLink.setBorderStyle(border);

				        annotationLink.setRectangle(position);
				        
				        PDActionGoTo actionGoto = new PDActionGoTo();
				        PDPageDestination dest = new PDPageFitWidthDestination();
				        PDPage currentPage = document.getDocumentCatalog().getPages().get(tocRec.getMergedFirstPage());
				        dest.setPage(currentPage);;
				        actionGoto.setDestination(dest); 

				        annotationLink.setAction(actionGoto);
     

				        document.getPage(currentTOCPage).getAnnotations().add(annotationLink);
				        
				        
			    	}`
