### ISSUE TITLE
Adding Images make PDF huge

### ISSUE THREAD

**Issue by axehigh** [dhorions/boxable#182]
I am trying to add images to a pdf in a table, and whenever I do, it seems the pdf-file "blows" up in size. Many times bigger than the original JPG. Is this a know issue?

When I add the file using PDImageXObject  it's fine, but really like that I don't have to worry about position the image, I can just add it to the cell (using createImageCell()).

**Comment by PiyushAuronia** [comment]
Hi,
I am facing the same issue. A 10 kb file explodes into 100 kb if i am using a cell. 
Is there something wrong that I am doing. I am creating the image from a byte array.
Thanks,
Piyush

**Comment by aislingvasey** [comment]
Yes, same problem. 
My PDF with same place holder image is -+800k. 
When I add the actual images which are 4MB outside of the document, the PDF ends up being 26.2MB in size. 
`protected void addImageCell(
            Row<PDPage> row,
            PDFont font,
            float imageCellWidth,
            File attachmentsFolder, File imagesFolder,
            String imageName,
            HorizontalAlignment imageAlignment,
            VerticalAlignment textVAlign,
            float scaleBy) throws IOException, SebenzanaException {
        if (SebenzanaUtil.isNotNullAndBlank(imageName)) {
            logger.debug("Adding image cell: " + imageName);
            File imageFile = getImageFile(attachmentsFolder, imagesFolder, imageName);
            Image theImage = ImageUtils.readImage(imageFile);
            theImage = theImage.scaleByHeight(theImage.getHeight() / scaleBy);
            // Image cell
            Cell<PDPage> cell = row.createImageCell(imageCellWidth, theImage, imageAlignment, VerticalAlignment.MIDDLE);
            cell.setTopPadding(5.0f);
        } else {
            logger.error("Invalid image to add to PDF!");
        }
    }`

**Comment by aislingvasey** [comment]
Image.draw():
If I pass in my image's file path and then change this line:
<pre>PDImageXObject imageXObject = LosslessFactory.createFromImage(doc, image);</pre>
to:
<pre>PDImageXObject imageXObject = PDImageXObject.createFromFile(imagePath, doc);</pre>
my generated PDF seems to be the correct size of 4.6MB with all the images.

**Comment by giboow** [comment]
I have a problem with my PDF's size too..
I add the same image many times, and the document "blows" up.
The real problem is when the image is draw.. the library add, every time, a new image to the PDF document.

```java
public void draw(final PDDocument doc, final PDPageContentStream stream, float x, float y) throws IOException {
	PDImageXObject imageXObject = LosslessFactory.createFromImage(doc, image);
	stream.drawImage(imageXObject, x, y - height, width, height);
}
```

I think it should add the image on the document only one time.

**Comment by giboow** [comment]
I just made the correction. The size of my PDF decreased from 2MB to 700KB
