### ISSUE TITLE
How to add image in Boxable table cell?

### ISSUE THREAD

**Issue by gajendraupadhyay1991** [dhorions/boxable#189]
Hi Team,
As per my project need, I need to add PNG image in Table Cell,
Please guide me, I'm new to PDFBox library.
Thanks in advance.

**Comment by dhorions** [comment]
Have a look at this [example](https://github.com/dhorions/boxable/blob/0b881e363fc3f6995acd840974e1ee3ef0d1022d/src/test/java/be/quodlibet/boxable/TableTest.java#L111)
