### ISSUE TITLE
Escape characters like \b or \f results in IllegalArgumentException error in PDF

### ISSUE THREAD

**Issue by ujetwani** [dhorions/boxable#198]
Hi, 

I am using below PDF font for encoding the special/escape characters in my Spring Boot Application. Some of the special characters gets encoded fine, however some characters like \b or \f results in IllegalArgumentException exception while inserting the data in PDF using boxable.
I followed the issue "Default font #73", still could not resolve the issue
Could you please provide a solution for this ?

**Code Snippet:**
				File arialbdttf = null;
				if(getClass() != null) {
					ClassLoader clasLoader = getClass().getClassLoader();
					if(null != clasLoader ) {
						//URL resurce = clasLoader.getResource("arialbd.ttf");
						URL resurce = clasLoader.getResource("freesansbold.ttf");
						if(resurce != null) {
							String arialFile = resurce.getFile();
							if( arialFile != null && !arialFile.isEmpty()) {
								arialbdttf = new File(arialFile);
							}
						}
					}
				}

**Comment by Frulenzo** [comment]
Can you give me cell text or just the part of it so I can run some test?
