### ISSUE TITLE
Useless extra space added in PdfTable and a few comments

### ISSUE THREAD

**Issue by Phiroc** [dhorions/boxable#2]
Hi,

the following line in PdfTable causes text in new columns to be shifted by an incremental extra space:

nextx += cell.getWidth() + HorizontalCellMargin;   

I have therefore replaced it by this line, in my code:

nextx += cell.getWidth(); 

The 'bookmark' variable is not used anywere in PdfTable. I have commented it out:
//bookmark = true;

The 'lines' List is not used in the code. I've commented it out:

// List<String> lines = cell.getParagraph().getLines();

I've added the following lines, respectively:

contentStream.setNonStrokingColor( Color.BLACK);
 -> contentStream.setLineWidth(HorizontalCellMargin);

contentStream.setNonStrokingColor(Color.BLACK);
-> contentStream.setLineWidth(VerticalCellMargin);

Please let me know what you think.

Cheers,

**Comment by Phiroc** [comment]
Hi,
sorry for taking so much time to reply, but I didn't  notice your notification until today.
I suggest the other changes because I would imagine that most developers would expect PDF tables to have visible lines.
Cheers,
Philippe

**Comment by dhorions** [comment]
These issues should be addressed in the most recent version.
