### ISSUE TITLE
inconsistent borders when PDF is opened in adobe acrobat pdf reader

### ISSUE THREAD

**Issue by vishal-vr-tfs** [dhorions/boxable#200]
first of all, thanks for the great project. I'm working on creating tables. everything is fine but when pdf is opened in adobe acrobat reader (zoom at 100%) borders look inconsistent. but when i zoom in border is there. so how to resolve this issue ? immediate help is needed.

order of setting cell styles.

`Cell<PDPage> otherVariantsCont = contentRow.createCell(10f, "");
			if(toggleCellFillColor) {
				otherVariantsCont.setFillColor(PdfReportConstants.customLightBlue);
			}
			otherVariantsCont.setTextColor(Color.black);
			otherVariantsCont.setFont(PDType1Font.HELVETICA);
			otherVariantsCont.setFontSize(PdfReportConstants.FONT_SIZE);
			otherVariantsCont.setBorderStyle(new LineStyle(PdfReportConstants.customBlue, 0.3f));`

<img width="1193" alt="Screenshot 2020-05-14 at 10 41 13 AM" src="https://user-images.githubusercontent.com/57786012/81895301-90e64380-95cf-11ea-9a21-e42615e4759e.png">

am i doing anything wrong ? plz let me know at earliest. thank you.

**Comment by vishal-vr-tfs** [comment]
@dhorions @Frulenzo

**Comment by Frulenzo** [comment]
Maybe you can make your border thicker? Sometimes Zoom In/Out is a little bit weird due line display but as long as you print the document and the lines are visible, I think everything is alright.
