### ISSUE TITLE
Custom Fixed column widths

### ISSUE THREAD

**Issue by mkgp00918** [dhorions/boxable#217]
Hi Team - This is a great library; but is there a way that the column widths can be controlled while adding tables to PDF from CSV ? 

Have looked at the library but seems like the addCSVToTable() calculates the width factor off the header length and font width.. Is there a way that the cell widths can be controlled based on the widths that we would need to have for the columns ?

Thanks

**Comment by CSchemmy** [comment]
The pullrequest #219 allows the width to be controlled. See DataTableTest.java and CSVexampleAdvanced.pdf. I hope it solves your problem
