### ISSUE TITLE
special character cause failure in the sample test.

### ISSUE THREAD

**Issue by dluzzon** [dhorions/boxable#22]
on sample1
getFacts()
facts.add(new String[]{"Tintin was conceived by Belgian artist Hergֳ©", "art", "celebrities", "inventions"});

there is special character here - Hergֳ©
this cause me the execution to fail:
java.lang.IllegalArgumentException: U+05B3 ('afii57802') is not available in this font's encoding: WinAnsiEncoding

once removed, all goes fine.

**comment**: appriciate what you have done, its realy great!

**Comment by Frulenzo** [comment]
You running latest TableTest? It's fine by me.

![specialk](https://cloud.githubusercontent.com/assets/4593056/13102980/791017b4-d552-11e5-8631-4bf5691ac3fd.png)

**Comment by dhorions** [comment]
The actual code is 
```
facts.add(new String[]{"Tintin was conceived by Belgian artist Hergé", "art", "celebrities", "inventions"});
```
So it might be a case of your system not recognizing the "é" correctly.

**Comment by Frulenzo** [comment]
Oh, I thought it was problem with © character. My bad.
Then @dhorions is probably right, your system doesn't recognize ```é``` correctly.

**Comment by dluzzon** [comment]
yes, probably.
thanks a lot.
