### ISSUE TITLE
Remove Guava as a compile dependency

### ISSUE THREAD

**Issue by agentgt** [dhorions/boxable#236]
Guava appears to be only used for test code

https://github.com/dhorions/boxable/search?q=google

Yet both the POM (and gradle) has it declared as 

`<scope>compile</scope>`

It should be:

`<scope>test</scope>`

**Comment by johnmanko** [comment]
Fixed with https://github.com/dhorions/boxable/commit/943e45363d1f19dc16e603cf80ada27799600546
