### ISSUE TITLE
font issue - getting exception

### ISSUE THREAD

**Issue by dluzzon** [dhorions/boxable#24]
Hi,
I have this code:
```
	public void createRow(MrtPackageRoute routeEntryValue) 
	{
		Row<PDPage> headerRow = this.createRow(10f);
        Cell<PDPage> cell;
       
        //Loan Type
        cell = headerRow.createCell((100 / 3), CommonUtil.getLocalValue(routeEntryValue.getRefLocalByRouteLoanType2local()));
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);

        //Amount
        cell = headerRow.createCell((100 / 6), Double.valueOf(routeEntryValue.getRouteLoanAmount()).toString());
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);
        
        //Years
        cell = headerRow.createCell((100 / 12), Double.valueOf(routeEntryValue.getRoutePeriodYears()).toString());
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);
        
        //Interest Rate
        cell = headerRow.createCell((100 / 12), Double.valueOf(routeEntryValue.getNominalInterestRate()).toString());
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);
        
        //Monthly Payment
        cell = headerRow.createCell((100 / 6), Double.valueOf(routeEntryValue.getRouteFirstPayment()).toString());
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);
        
        cell = headerRow.createCell((100 / 6), CommonUtil.getLocalValue(routeEntryValue.getRefLocalByCalcMethod2local()));
        cell.setFont(PDType1Font.TIMES_ROMAN);
        cell.setFontSize(6);
	}
}
```

when code is coming to:
`table.draw();`

getting the below exception. assuming it is font issue.
I'm using Hebrew.
**What need to be done in order to support it?**

**Exception**
00:03:58,409 WARN  [org.apache.pdfbox.pdmodel.font.PDType1Font] (default task-2) Using fallback font ArialMT for base font ZapfDingbats
00:03:58,439 ERROR [stderr] (default task-2) java.lang.IllegalArgumentException: U+05DE ('afii57678') is not available in this font's encoding: WinAnsiEncoding

00:03:58,439 ERROR [stderr] (default task-2) 	at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:345)

00:03:58,439 ERROR [stderr] (default task-2) 	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:285)

00:03:58,440 ERROR [stderr] (default task-2) 	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:314)

**Comment by dluzzon** [comment]
after more investigation, looks there is some issue with boxtable
with this sample class, able to write:

```
package pdfProj.test;


import java.io.File;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType0Font;

public class utftext {

    public static void main(String[] args) throws Exception {
        PDDocument document = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        document.addPage(page);
        File tnrFontFile = new File("c://temp//font//times.ttf");
        PDType0Font font = PDType0Font.load(document, tnrFontFile);
        PDPageContentStream stream = new PDPageContentStream(document, page);
        String text = "Hello שלום";
        stream.beginText();
        stream.setFont(font, 12);
        stream.moveTextPositionByAmount(50, 600);
        stream.drawString(text);
        stream.endText();
        stream.close();
        document.save("c://temp//pdf//type0_1.pdf");
        document.close();
    }

}
```

but when doing the same with boxtable
```
File tnrFontFile = new File("c://temp//font//times.ttf");
tnrFont = PDType0Font.load(document, tnrFontFile);

``` 
somehow it overide the **PDType0Font **and uses the **PDType1Font **and than getting the below exception:

> 22:18:05,026 WARN  [org.apache.pdfbox.pdmodel.font.**PDType1Font**] (default task-2) Using fallback font **ArialMT **for base font ZapfDingbats
> 22:18:05,078 ERROR [stderr] (default task-2) java.lang.IllegalArgumentException: U+05DE ('afii57678') is not available in this font's encoding: WinAnsiEncoding
>

**Comment by dobluth** [comment]
From a quick look at it, I am wondering why you are loading the Times New Roman font. Can't you just use ```PDType1Font.TIMES_ROMAN```?

**Comment by dluzzon** [comment]
Hi,
because the function I'm using return Hebrew letters.
Hebrew letters are not supported with PDType1Font.TIMES_ROMAN.

There must be a way to add new font.
else the boxable will not support lot of languages.
I saw on the BaseTable there is a hook something like loadFont that can be
overridden. is it related?
how the implementation of it should be defined?

This is critical issue for me.
Appreciate your help.

**Comment by dobluth** [comment]
After some further digging, I think I know what happens. The font used for bold text as in the header row is per default ```PDType1Font.HELVETICA_BOLD```, which cannot be used for the characters in your test string. In the PR #26 the method ```Cell.setFontBold(PDFont)``` is added to overwrite this value.

At least in my local test case this is working now. Could you please try it?

**Comment by dobluth** [comment]
Please set the same font twice via:
```java
cell.setFont(timesFont);
cell.setFontBold(timesFont);
```
This is due to another issue I cannot fix that fast.

**Comment by dluzzon** [comment]
Hi Markus,

 

No such method setFontBold

**Comment by dluzzon** [comment]
you are right the problem is with the header.
issue came when using:
`table.setHeader(headerRow);`

regarding the cell.setFontBold(font), no such method:
![setfontbold_no_such_method](https://cloud.githubusercontent.com/assets/13005759/13403696/fef456ee-df1e-11e5-81ef-80a3dbdf88f9.png)

**Comment by dluzzon** [comment]
just notice its a new method, will update my code.
thanks a lot!

**Comment by dluzzon** [comment]
working fine with the cell fix.
Thanks a lot.

**Comment by dobluth** [comment]
Glad I could help :)
