### ISSUE TITLE
Boxable is creating table on a new page instead of the current page

### ISSUE THREAD

**Issue by avaiyahardik** [dhorions/boxable#244]
I am trying to create a table in pdf using Boxable and it is creating table in a new page instead of the current page.

BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,
				drawContent);
//Create Header row
Row<PDPage> headerRow = table.createRow(15f);
Cell<PDPage> cell = headerRow.createCell(100, "Awesome Facts About Belgium");
cell.setFont(PDType1Font.HELVETICA_BOLD);
cell.setFillColor(Color.BLACK);
table.addHeaderRow(headerRow);
List<String[]> facts = getFacts();
for (String[] fact : facts) {
			Row<PDPage> row = table.createRow(10f);
			cell = row.createCell((100 / 3.0f) * 2, fact[0] );
			for (int i = 1; i < fact.length; i++) {
			   cell = row.createCell((100 / 9f), fact[i]);
			}
}
table.draw();

**Comment by avaiyahardik** [comment]
> I am trying to create a table in pdf using Boxable and it is creating table in a new page instead of the current page.
> 
> BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,
> drawContent);
> //Create Header row
> Row headerRow = table.createRow(15f);
> Cell cell = headerRow.createCell(100, "Awesome Facts About Belgium");
> cell.setFont(PDType1Font.HELVETICA_BOLD);
> cell.setFillColor(Color.BLACK);
> table.addHeaderRow(headerRow);
> List<String[]> facts = getFacts();
> for (String[] fact : facts) {
> Row row = table.createRow(10f);
> cell = row.createCell((100 / 3.0f) * 2, fact[0] );
> for (int i = 1; i < fact.length; i++) {
> cell = row.createCell((100 / 9f), fact[i]);
> }
> }
> table.draw();

I was using incorrectly. It is working.

**Comment by arjitm786** [comment]
Hi @avaiyahardik , I'm having the same issue. Can you tell me how to change it so that I can create table on the same page.

**Comment by FoxWD** [comment]
Hi @avaiyahardik , I'm having the same Issue, if you can tell me how to change it so that I can create table on the same page.

**Comment by FoxWD** [comment]
Eureka, I've found the solution, you have to play with yStart
