### ISSUE TITLE
NoSuchFieldError: HELVETICA

### ISSUE THREAD

**Issue by RachidLeLaborantin** [dhorions/boxable#256]
Hi, thanks for your projects it's useful and amazing. It will help me
But I have an exception when I try to create a cell from Row.create class. It says, NoSuchFieldError: HELVETICA

Hope your reply

**Comment by RachidLeLaborantin** [comment]
I think I know where do this exception coming. You used an old version of PdfBox where the default font HELVETICA is in PDTypeFont1 class 
But in the new version that I'm currently using, it was moved to another class cause I searched it the previous class I didn't found

I found it in Standard14Font.fontname.HELVETICA


I think that you should update your library 

Thanks

**Comment by johnmanko** [comment]
> You used an old version of PdfBox

Which version of boxable are you using?  Version `1.7.0` was just released.

**Comment by RachidLeLaborantin** [comment]
I have implemented it two days ago thus it's the latest version I use
But your library don't use latest versions of PdfBox 


Another issue is that, I want to change the cells border color. I want to keep the line border but change the color
The borders you gave is dashed and dotted and I don't want it

**Comment by RachidLeLaborantin** [comment]
It's when I used old version of PdfBox which is 2.2... that it worked
But for last 3.0.0 version it doesn't
