### ISSUE TITLE
Column width incorrectly calculated

### ISSUE THREAD

**Issue by DrFlibble** [dhorions/boxable#259]
I've just hit a bug where I have a table with a single row and column of the word "Backback" (Which itself is a typo of Backpack!). It always throws an exception:

```
java.lang.IllegalArgumentException: Cell Width=495.27567 can't be bigger than row width=495.27563
	at be.quodlibet.boxable.Cell.<init>(Cell.java:107) ~[boxable-1.7.0.jar:na]
	at be.quodlibet.boxable.Row.createCell(Row.java:134) ~[boxable-1.7.0.jar:na]
	at be.quodlibet.boxable.datatable.DataTable.addCsvToTable(DataTable.java:266) ~[boxable-1.7.0.jar:na]
	at be.quodlibet.boxable.datatable.DataTable.addListToTable(DataTable.java:204) ~[boxable-1.7.0.jar:na]
```

After stepping through with a debugger,  it appears that there's an error with rounding of the sizefactor in DataTable.addCsvToTable, which gives a widthPct of 100.00001, which obviously leads to the width being too wide later on.

<img width="1167" alt="Screenshot 2022-09-17 at 12 49 10" src="https://user-images.githubusercontent.com/4589414/190855232-d3293b23-811d-4bf0-8799-0205cec96822.png">

Should this widthPct be limited to 100%?

For now, I'll fix the typo :-)

Ian

**Comment by johnmanko** [comment]
@DrFlibble Can you provide a PR for this?

**Comment by nstdspace** [comment]
I [did so](https://github.com/dhorions/boxable/pull/263) back in winter last year after finding the same bug. 
In the PR I changed the calculation order to prevent rounding error influence but I can additionally limit the width to 100%.
But it seems that PR's are not getting reviewed and the project isn't active anymore..?

**Comment by johnmanko** [comment]
https://github.com/dhorions/boxable/pull/263
