### ISSUE TITLE
Github 2FA - Goodbye

### ISSUE THREAD

**Issue by johnmanko** [dhorions/boxable#269]
~~Github is now requiring Two-Factor Auth.  I'm not interested in giving them my phone number or installing their application.  I'll probably end up deleting my GH account.~~

~~I just wanted to let you know so someone else can contribute.~~

~~Goodbye.~~

**Comment by spellman** [comment]
FWIW, I use a one-time-password-generator authenticator app as my second authentication factor. I use the Google app but there are others available.

**Comment by ztNFny** [comment]
> I'm not interested in giving them my phone number or installing their application. I'll probably end up deleting my GH account.

There are hundreds of TOTP apps out there, many of them open-source. No need to install githubs app or give them your phone number.

**Comment by johnmanko** [comment]
> > I'm not interested in giving them my phone number or installing their application. I'll probably end up deleting my GH account.
> 
> There are hundreds of TOTP apps out there, many of them open-source. No need to install githubs app or give them your phone number.

I just found one.  Thanks for the tip.  I thought I had to give Github my number and/or install their app, which I wasn't going to do.
