### ISSUE TITLE
BaseTable - override not done properly

### ISSUE THREAD

**Issue by dluzzon** [dhorions/boxable#27]
should be
```
@Override
    protected void loadFonts() throws IOException{
        // Do nothing as we don't have any fonts to load
    }
```
instead of 
```
@Override
    protected void loadFonts() {
        // Do nothing as we don't have any fonts to load
    }
```

**Comment by dobluth** [comment]
Yes, you are right. I cannot explain how that could happen.

However, I would be happy to get rid fo this mechanism, as it forces the constructors (of `Table` and `BaseTable`) to throw an `IOException`. I don't like constructors that throw a checked exception.

Also, I am wondering, why someone should load fonts in a table, and not in the code that builds the PDF, unless your PDF only contains that single table.

**Comment by dluzzon** [comment]
Yes, agree, better to load the font for the entire pdf once once. J

**Comment by dhorions** [comment]
Version (1.3)[https://github.com/dhorions/boxable/releases] is released and resolves these issues.
