### ISSUE TITLE
Poor performance addListToTable

### ISSUE THREAD

**Issue by dev-comrade** [dhorions/boxable#273]
Hi.

I realized a poor performance with method addListToTable in DataTable when it takes a lot of data.

I found the reason. You should fix method addListToTable like this:

```java
public void addListToTable(List<List> data, Boolean hasHeader) throws IOException {
	if (data == null || data.isEmpty()) {
		return;
	}
	StringBuilder output = new StringBuilder();
	char separator = ';';

        // Convert Map of arbitrary objects to a csv String
	for (List<? extends Object> inputList : data) {
		StringBuilder row = new StringBuilder();
		for (Object v : inputList) {
			String value = v.toString();
			if (value.contains("" + separator)) {
				// surround value with quotes if it contains the escape
				// character
				value = "\"" + value + "\"";
			}
                        value = value.replaceAll("\n", "<br>");
			row.append(value).append(separator);
		}
		// remove the last separator
		row = new StringBuilder(row.substring(0, row.length() - 1));
		output.append(row).append("\n");
	}

	addCsvToTable(output.toString(), hasHeader, separator);
}
```

You should build a string from each object, then remove last char and then append this new string to final result. But in your realization, all of new objects are appending to final string and then cutting last char, in this case when you have a lot of rows, each iteration takes more and more time. My code fix it and increase performance by 90% with large amount of data.

**Comment by johnmanko** [comment]
Can yo provide benchmark caparisons for a couple quantities of data?  I'd like to see the numbers.

**Comment by dev-comrade** [comment]
> @dev-comrade Can you provide benchmark caparisons for a couple quantities of data? I'd like to see the numbers.

sorry, I thought it was obvious that the current algorithm <s>sucks</s> bad :smile: 

i wrote a little example: https://github.com/dev-comrade/boxable-test
