### ISSUE TITLE
Boaxable on Maven Central

### ISSUE THREAD

**Issue by Blackbilbao** [dhorions/boxable#36]
Hi, 

Due to some contraints we would like to use reposetoeries which are hostet on maven central...

is it possible (or planned) that you will maybe transsion from jitpack to maven in the near future?

**Comment by dhorions** [comment]
Hi,

I'm trying to jump to the necessary hoops to get this done.  At this point unsure how long it will take since this is my first time.


Dries

**Comment by dhorions** [comment]
Hi, you can now find boxable on maven central [here](http://search.maven.org/#artifactdetails%7Ccom.github.dhorions%7Cboxable%7C1.3%7Cjar)

```xml
<dependency>
    <groupId>com.github.dhorions</groupId>
    <artifactId>boxable</artifactId>
    <version>1.3</version>
</dependency>
```

**Comment by Blackbilbao** [comment]
Thanks alot :)
