### ISSUE TITLE
Please review - Add tables to pdf from csv

### ISSUE THREAD

**Issue by dhorions** [dhorions/boxable#40]
Hi,

this weekend I spent some time on creating a feature that I think would make this library a lot more helpful and easier to use.

I added the ability to load data from a csv-file and add that to a table in a pdf format.
The changes are in [this branch](https://github.com/dhorions/boxable/tree/csv_handling).

In it's most basic form, it can be used like this : 
```java
BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,true);
CSVTable t = new CSVTable(dataTable, page);
t.addCsvToTable(data, CSVTable.HASHEADER, ';');
dataTable.draw();
```
The output of that will look like this : 
![image](https://cloud.githubusercontent.com/assets/1682004/14228745/26de3796-f91f-11e5-9500-5ba9cefc7407.png)

[CSVexampleLandscape.pdf](https://github.com/dhorions/boxable/files/201008/CSVexampleLandscape.pdf)

But, there is also the ability to add other content to the table, and to apply a different format to the header row, first column, last colum, odd rows and even rows.

```java
BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true, true);
//Add a few things to the table that's not coming from the csv file
Row h1 = dataTable.createRow(0f);
Cell c1 = h1.createCell(100, "Electricity Prices by type of user");
c1.setFillColor(new Color(144, 195, 212));
dataTable.addHeaderRow(h1);
Row h2 = dataTable.createRow(0f);
Cell c2 = h2.createCell(100, "Eur per kWh for Medium Size Households.<br/>Source <i>http://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&plugin=1&language=en&pcode=ten00117</i>");
c2.setFillColor(new Color(175, 212, 224));
dataTable.addHeaderRow(h2);
CSVTable t = new CSVTable(dataTable, page);
//set the style template for header cells
t.getHeaderCellTemplate().setFillColor(new Color(13, 164, 214));
//set the style template for first column
t.getFirstColumnCellTemplate().setFillColor(new Color(13, 164, 214));
//set the style template for last column
t.getLastColumnCellTemplate().setFillColor(new Color(144, 195, 212));
//set the style template for normal, data columns
t.getDataCellTemplateEven().setFillColor(Color.WHITE);
t.getDataCellTemplateOdd().setFillColor(new Color(250, 242, 242));
t.addCsvToTable(data, CSVTable.HASHEADER,';');
 dataTable.draw();
```
The output of that will look like this : 
![image](https://cloud.githubusercontent.com/assets/1682004/14228760/74385936-f91f-11e5-8064-fc0323ab662c.png)

[CSVexampleAdvanced.pdf](https://github.com/dhorions/boxable/files/201009/CSVexampleAdvanced.pdf)

I'm looking forward to any feedback on the usage, any issues found testing, and any advice on default colors.  I'm really bad at combining colors :)

**Comment by dhorions** [comment]
Perhaps in addition to csv we can also implement the same functionality for Lists/arrays of Maps or Json Lists or Arrays.

**Comment by dhorions** [comment]
It turns out using the csv functionality to a way to just render Lists of Lists of Objects to a pdf table was pretty simple.

```java
//Create the data
List<List> data = new ArrayList();
data.add(new ArrayList<>(
               Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));
for (int i = 1; i <= 100; i++) {
  data.add(new ArrayList<>(
               Arrays.asList("Row " + i + " Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
}
BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true,true);
CSVTable t = new CSVTable(dataTable, page);
t.addListToTable(data, CSVTable.HASHEADER);
dataTable.draw();
```
![image](https://cloud.githubusercontent.com/assets/1682004/14232022/28937300-f99a-11e5-9425-1254d01e7fa4.png)

[ListExampleLandscape.pdf](https://github.com/dhorions/boxable/files/201280/ListExampleLandscape.pdf)

**Comment by dobluth** [comment]
Hi Dries,

this looks like a very nice feature, good work! :)
