### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by derfsubterfuge** [dhorions/boxable#43]
Is there a way to add line breaks to text in cells?

I've tried things like this, but I keep getting an encoding error:
`row = table.createRow(10f);
 cell = row.createCell(100, "test1\ntest2");`

Note: In PDFBox, you write new line characters by calling PDPageContentStream.newLine().

Thanks,
Nicholas Castorina

**Comment by Frulenzo** [comment]
You can do it with HTML tags `<br />` or `<br>`

**Comment by derfsubterfuge** [comment]
<br> and <br /> don't appear to work.

**Comment by Frulenzo** [comment]
Hmmm that's weird. Are you sure on last stand? I will do some test tomorrow and let you know

**Comment by dobluth** [comment]
There is no release yet including PR #34, but it is already merged into master. If you are building Boxable yourself using the code, ensure you have the latest changes. If you are including Boxable via Maven repository, I guess you have to wait until @dhorions creates a new release.

**Comment by Frulenzo** [comment]
Almost certain is the reason what @dobluth has mentioned. I just tested with this code and all seems to work.

```java
[...]
Row<PDPage> row2 = table.createRow(15f);
		Cell<PDPage> cell4 = row2.createCell((100 / 3.0f), " <p>Integer eget<br> elit vitae est feugiat laoreet.<br><b>Nam vitae ex commodo, euismod risus in, sodales dolor. Mauris condimentum urna neque, non condimentum odio</b> posuere a. Aenean nisl ex, semper eu malesuada sit amet, luctus nec enim. <br>Pellentesque eu<br> ultrices magna, non porta dolor. Fus<b><i>ce eu neque nulla. Curabitur eu eros tristique leo efficitur fringilla sit amet sed neque. Aliquam</i></b> a tempor enim. Praesent pellentesque<br> volutpat dolor, non rhoncus est posuere id. Aenean nunc purus, gravida at mauris et, pretium volutpat nisl. Mauris lacus urna, sodales ac eros in, mollis scelerisque neque.</p> Unordered List <ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul>", HorizontalAlignment.get("center"),
				VerticalAlignment.get("top"));
		cell4.setFontSize(6);
[...]
```
Result
[brExample.pdf](https://github.com/dhorions/boxable/files/203916/brExample.pdf)

**Comment by dhorions** [comment]
1.4 will be released today.

**Comment by dhorions** [comment]
1.4 was released, use the following dependency with maven
```xml
<dependency>
    <groupId>com.github.dhorions</groupId>
    <artifactId>boxable</artifactId>
    <version>1.4</version>
</dependency>
```
