### ISSUE TITLE
paging on table overflow broken 

### ISSUE THREAD

**Issue by tunichgud** [dhorions/boxable#5]
Hi,

i just realized that if a table is larger then the current page, the code does not result in correctly creating a new page.

i fixed this issue locally for me. It's because the createPage() method in BaseTable (boxable/src/main/java/be/quodlibet/boxable/BaseTable.java)  is missing a document.add(page)

    @Override
    protected PDPage createPage() {
        PDPage page = new PDPage();
        this.getDocument().addPage(page);
        return page;
    }

this did the trick for me. 

cheers tunichgood

**Comment by Kravs** [comment]
But how does examples works?

https://github.com/dhorions/boxable/blob/master/src/test/java/be/quodlibet/boxable/TableTest.java

**Comment by tunichgud** [comment]
for me, they don't.

**Comment by tunichgud** [comment]
the examples don't use the feature to automatically create a new page, if the content doesn't fit on the page anymore.

**Comment by tunichgud** [comment]
@Test
	public void shouldUseCreationOfNewPagesOnContentAdding() throws IOException, COSVisitorException {

		// Set margins
		float margin = 10;

		List<String[]> facts = getFacts();

		// Initialize Document
		PDDocument doc = new PDDocument();
		PDPage page = addNewPage(doc);
		float yStartNewPage = page.findMediaBox().getHeight() - (2 * margin);

		// Initialize table
		float tableWidth = page.findMediaBox().getWidth() - (2 * margin);
		CONTENT drawContent = CONTENT.DRAW;
		float yStart = yStartNewPage;
		float bottomMargin = 70;
		BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin,
				tableWidth, margin, doc, page, LINES.DRAW, drawContent);

		// Create Header row
		Row headerRow = table.createRow(15f);
		Cell cell = headerRow.createCell(100, "Awesome Facts About Belgium");
		cell.setFont(PDType1Font.HELVETICA_BOLD);
		cell.setFillColor(Color.BLACK);
		cell.setTextColor(Color.WHITE);

		table.setHeader(headerRow);

		// Create 2 column row
		Row row = table.createRow(15f);
		cell = row.createCell(30, "Source:");
		cell.setFont(PDType1Font.HELVETICA);

		cell = row.createCell(70, "http://www.factsofbelgium.com/");
		cell.setFont(PDType1Font.HELVETICA_OBLIQUE);

		// Create Fact header row
		Row factHeaderrow = table.createRow(15f);

		cell = factHeaderrow.createCell((100 / 3) * 2, "Fact");
		cell.setFont(PDType1Font.HELVETICA);
		cell.setFontSize(6);
		cell.setFillColor(Color.LIGHT_GRAY);

		cell = factHeaderrow.createCell((100 / 3), "Tags");
		cell.setFillColor(Color.LIGHT_GRAY);
		cell.setFont(PDType1Font.HELVETICA_OBLIQUE);
		cell.setFontSize(6);

		// Add multiple rows with random facts about Belgium
		for (int k = 0; k < 5; k++) {
			for (String[] fact : facts) {

				row = table.createRow(10f);
				cell = row.createCell((100 / 3) * 2, fact[0]);
				cell.setFont(PDType1Font.HELVETICA);
				cell.setFontSize(6);

				for (int i = 1; i < fact.length; i++) {

					cell = row.createCell((100 / 9), fact[i]);
					cell.setFont(PDType1Font.HELVETICA_OBLIQUE);
					cell.setFontSize(6);
					// Set colors
					if (fact[i].contains("beer"))
						cell.setFillColor(Color.yellow);
					if (fact[i].contains("champion"))
						cell.setTextColor(Color.GREEN);
				}
			}
		}

		table.draw();

		// Close Stream and save pdf
		File file = new File("target/BoxableSample1.pdf");
		Files.createParentDirs(file);
		
		 Assert.assertEquals(15, doc.getPageCount()); // this will fail

		doc.save(file);
		
		doc.close();
	}

**Comment by tunichgud** [comment]
try this test, you will see, it will result in the creation of only one page. use my patch, you will have 15 pages.

**Comment by Kravs** [comment]
Ok, I will try.
I was confused by this example:
https://s3.amazonaws.com/misc.quodlibet.be/Boxable/Boxable_example1.pdf
I think it is not up to date.

I hope it will be updated, because plugin is usefull)

**Comment by Kravs** [comment]
Is this project alive ?
PR is not accepted or declined. Issueas are not closer...
So sad :(

**Comment by dhorions** [comment]
I just got back from vacation, my apologies for not responding sooner.  Once it get caught up on other things I'll address all boxable issues.

**Comment by Kravs** [comment]
@dhorions Ok, thank you for response!
So in that case please take a look at issue regarding maven repository, I really need to have boxable as dependencies.

And I start my work on it, so soon there will be some pull requests :)

**Comment by tunichgud** [comment]
I meanwhile forked boxable, integrated it in my build environment and artifactory. If I wouldn't have to host this on my own, I'd be very happy.

**Comment by dhorions** [comment]
The paging issue was fixed by https://github.com/dhorions/boxable/commit/78ffbbd99f251af425ae4bdbdd41bb3dbc97db9b .

I'll be adding a way to use it as a maven dependency soon, check the main page later today.

**Comment by Kravs** [comment]
Thank you!

**Comment by dhorions** [comment]
Info on how to use it as a dependency added to [readme](https://github.com/dhorions/boxable/blob/master/README.md)

**Comment by Lebrero** [comment]
Hi, I have he same problem. I create a table and set a margin... and when overflows... the next pages have this margin too...How i can fix if... its importante please!!!

**Comment by Frulenzo** [comment]
Can you provide test case and PDF? Where is the problem with margin on next page? Isn't that what we always want? to maintain margin on all pages?
