### ISSUE TITLE
Page Breaking with multiple Tables on the Same Page (Horizontal)

### ISSUE THREAD

**Issue by Blackbilbao** [dhorions/boxable#57]
hi Guys,

i have encountered the following problem,

i try to have 2 tables side by side on one Page.

In the middle of the first page you see a section called "Bauteil Position 4 Typ : 415

if the left table is small enough everthing works as expected.

(see example2 )
[Example 2.pdf](https://github.com/dhorions/boxable/files/254589/Example.2.pdf)

if on the other hand the table on the left (which is always bigger than the one on the right) breaks i'm not sure how to display the secound tale (right one) correctly..

what happens is that table left causes a page break and creates a new page. the right table which starts on the same page at the same hight also want to generate a page break... some how i have to tell the secound page to which page it should pagebreak if necessary.

(see example for the prolem)
[Example.pdf](https://github.com/dhorions/boxable/files/254582/Example.pdf)

Does somebody have a clue how to fix this problem?

**Comment by dobluth** [comment]
Hi,

which version of Boxable are you using? Because the current (1.4) `DefaultPageProvider` should be capable of navigating through the pages of the document, creating pages only if it would exceed the document.

**Comment by Blackbilbao** [comment]
i'm using the 1.4 version.

maybe i'm doing something wrong...

i genrate 2 tables in 2 diffrent methods.. 

first i draw the first one without anything special, rembering the curY position and if the page is broken i rember the old and the new page so that the conntent after the break goes to the new page

then i draw the secound table at the same position as the first table (and page) and then i  also rember where the break (if happend) is..

After that if a break happend i continue to draw on the new page if not then i just go on with the next table

If both tabels produce a break my table continues on the right table last position (becuase if the first one has a break i rember the new page and if the secound also breaks i rember its new page) ... that is why i have an almost empty page...

some how i have to tell the right table that if a break already happend it should not generate its own new page and rather use the new page from the left table. but i see no option to do that...

**Comment by dobluth** [comment]
Your algorithm sounds fine. I assume you remember the pages outside the `PageProvider`, so `PageProvider.nextPage()` cannot determine that it already has created the page and can re-use it.

Please try the following page provider:
```java
public class MyPageProvider implements PageProvider<PDPage> {

    private final PDDocument document;

	private final PDRectangle size;

	private int currentPageIndex = -1;

	public MyPageProvider(final PDDocument document, final PDRectangle size) {
		this.document = document;
		this.size = size;
	}

	@Override
	public PDDocument getDocument() {
		return document;
	}

	@Override
	public PDPage createPage() {
		currentPageIndex = document.getNumberOfPages();
		return getCurrentPage();
	}

	@Override
	public PDPage nextPage() {
		if (currentPageIndex == -1) {
			currentPageIndex = document.getNumberOfPages();
		} else {
			currentPageIndex++;
		}

		return getCurrentPage();
	}

	@Override
	public PDPage previousPage() {
		currentPageIndex--;
		if (currentPageIndex < 0) {
			currentPageIndex = 0;
		}

		return getCurrentPage();
	}

	private PDPage getCurrentPage() {
		if (currentPageIndex >= document.getNumberOfPages()) {
			final PDPage newPage = new PDPage(size);
			document.addPage(newPage);
			return newPage;
		}

		return document.getPage(currentPageIndex);
	}

    public PDPage selectPage(final int index) {
        currentPageIndex = index;
        if (currentPageIndex < 0) {
            currentPageIndex = 0;
        }
        if (currentPageIndex >= document.getNumberOfPages()) {
            currentPageIndex = document.getNumberOfPages() - 1;
        }
		
        return getCurrentPage();
    }

    public int getCurrentPageIndex() {
        return currentPageIndex;
    }
}
```

It has two more methods than the `DefaultPageProvider`:

1. `getCurrentPageIndex()`: Use it to remember the page, so just remember the index instead of the page (using the index also has the advantage that you can use `Math.max()` to choose the page created by the biggest table, even if it spans several pages)
2. `selectPage()`: use this method to select the page you remembered with the former method, just before drawing the right page

Use this page provider by passing it as an argument to the respective Table constructors.

I hope this helps. Feel free to ask in case something is unclear.

**Comment by Blackbilbao** [comment]
so i played a bit with the PageProvider.. and i get exactly the same result

i've changed so far

before goning into the method where to draw the two tables i rember the current page

then in the first table i added the pageprovider and instead of the normal Page i tell th BaseTable to use myprovider.selectPage(currentPageIndex)

i do the same with the second table..

after both tabels i check 

`if (currentPageIndex != myPageProvider.getCurrentPageIndex())
				{
					if (messung > echodaempf)
					{
						curY = messung;
					}
					else
					{
						curY = echodaempf;
					}

					currentPageIndex = myPageProvider.getCurrentPageIndex();
					myPageProvider.selectPage(currentPageIndex);
				}`

but this results again in an half empty page...

**Comment by dobluth** [comment]
I was not able to follow your description above in all details.

Could you please confirm that your code roughly follows the following "pseudo" code?

```java
// setup page provider and the first page
MyPageProvider pageProvider = new MyPageProvider(document, size);
PDPage page = pageProvider.nextPage();

// this is the page index of the page on which each table should start drawing
int pageIndex = pageProvider.getCurrentPageIndex();

// remember which was the furthest position
int maxPageIndex;
float maxY;

// setup and draw first table
BaseTable table = new BaseTable(..., document, page, ..., pageProvider);
...
float y = table.draw();

// as it is the only table, it is by definition the longest, so just take the values
maxY = y;
maxPageIndex = pageProvider.getCurrentPageIndex();

// back to the first page (the page variable should not change here)
page = pageProvider.selectPage(pageIndex);

// setup and draw second table
BaseTable table2 = new BaseTable(..., document, page, ..., pageProvider);
...
y = table2.draw();

// was this a bigger table?
if (pageProvider.getCurrentPageIndex() > maxPageIndex) {
    maxPageIndex = pageProvider.getCurrentPageIndex();
    maxY = y;
} else if (pageProvider.getCurrentPageIndex() == maxPageIndex && y < maxY) {
    maxY = y;
}

// now we should be able to continue drawing behind the longest table
page = pageProvider.selectPage(maxPageIndex);
PDPageContentStream stream = new PDPageContentStream(document, page, true, true);
PDStreamUtils.write(stream, "I am down here", ..., maxY, ...);
stream.close();
```

**Comment by Blackbilbao** [comment]
okay.. first:
Yes my code kinda works like that..

i know changed all the tables to tables with page providder and now it works ... :)

apperantly i had a bug somewhere 

but the pageprovider did the trick now the tables look like i wanted them to :D

Thanks alot

**Comment by dobluth** [comment]
Great! I am glad that it worked!

**Comment by dhorions** [comment]
Happy to see this is resolved.

**Comment by poojabagade** [comment]
Can you provide the full working code
