### ISSUE TITLE
how to get table height dynamically

### ISSUE THREAD

**Issue by ErickPezoa** [dhorions/boxable#61]
I am creating tables using PDFBOX Boxable library. The table height will depend on how much data there in a database. If I have two tables one after the other, I need to know the table height of the first one so that I can draw the next one just below it. How can I find the table height from the previous table?

Also, if there table (or some content inside the page) reaches to the end of the page, how can I tell the system to automatically create a second page?

Please let me know!

**Comment by dobluth** [comment]
Hi Erick,

what you need is the y position after drawing the first table, which ist the return value of the `draw()` method:
```java
float newYPosition = table.draw();
```

Page breaks happen automatically if the table exceeds the page. If you need to create pages manually you have to use a `PageProvider`, which has to be passed as parameter to the `Table` constructor. You can use the method `PageProvider.createPage()` to create a new page. For your use case the `DefaultPageProvider` should be sufficient.

Side note: If you plan to draw tables side by side, please take a look at #57 (which explains the general procedure as well as a custom `PageProvider`).

Markus

**Comment by srikkar** [comment]
hi Dobluth,

I'm developing  the similar code, data will be fetched from multiple tables and written to PDF.
So, Im getting resultSets and passing it to different writePDF methods to populate content in tables from reslutSet.

by using float newYPosition = table.draw();
I got the new Y position and with some buffer, I tried inserting new table with same PDPage. 
Now, I see the content written first disappeared and only second table is shown.

Any suggestions/observations please.

**Comment by srikkar** [comment]
Hi Dobluth,

I found it.

Before the table I have opened a contentstream without appender.

Thanks, this post helped me to getting the height remaining without spending time on height consumned by Table  :+1:
