### ISSUE TITLE
adding line break inside a column, question about fonts and multiple rows within a cell

### ISSUE THREAD

**Issue by ErickPezoa** [dhorions/boxable#62]
Given a cell, like follows: `cell = row.createCell(20, "Email: " + bean.getEmail())`, how can I put a line break between Email and the variable bean.getEmail()? 

I know, for example, that to make the Email word bold, I could do: `row.createCell(20, "<b>Email:<b> " + bean.getEmail())` but I haven't been able to figure out how to make a line break.

Also, do I have other font options besides the one available in the class `PDType1Font`?

In the attached image I present an example of what I am trying to do when it comes to having multiple rows within a cell. Please see what the red arrows is pointing to. Can I accomplish that using Boxable?

![multiple_rows_within_cell](https://cloud.githubusercontent.com/assets/6473137/15640048/2e9b44b0-2601-11e6-8a76-01ab88c33cec.jpg)

**Comment by dobluth** [comment]
Hi Erick,

to generate a line break, you can use HTML tags, too (`<br>`):
```java
row.createCell(20, "<b>Email:<b><br> " + bean.getEmail())
```
---

You can use another `PDFont`, just load it, for example:
```java
PDFont font = PDType0Font.load(document, fontFile);
```

---

I see three options to generate an output like in your image:
1. A table within a table (not possible with Boxable)
2. rowspan (not (yet) possible with Boxable, see #39)
3. try to fake a rowspan ;)

To fake such a table you would have to generate 3 rows ("Grupo Familiar", "Adicionales", "Costo Total"). In the columns "Plan seleccionado" and "Código de Plan" you draw no borders between rows 1/2 and rows 2/3. It gets harder if you have some text in those two columns, as there are still three rows, leading to the question: where do you output it? But as long as there is no text, you should be fine ;)

Markus

**Comment by Frulenzo** [comment]
Just a quick correction with ``<b>`` tag. If you don't want your email adress also be bold then you need to write:
```java
row.createCell(20, "<b>Email:</b><br> " + bean.getEmail())
```
because if yout don't close your bold text in your previous line, it will be carried in your next line.

Other thing, I also think that you will need to apply @dobluth third solution. It's not so "clean" but hopefully that solves your current problem.

**Comment by dobluth** [comment]
Good catch, my brain auto-corrected it to a closing tag :D

**Comment by dhorions** [comment]
Glad to see this is resolved.

**Comment by ErickPezoa** [comment]
I am having another big issue that I hope you guys can help me with. I need to solve it because I need to deliver to a client.

I will be sending in an hour or so the code and sample pdf to demonstrate the problem. 

Regards,

Erick Pezoa.

**Comment by ErickPezoa** [comment]
Ok guys. Checkout the attached code and PDF sample. I think it is clear
what the problem is. If you look in the code, I have 4 BaseTable instances.
The third BaseTable has a dynamic height (It depends on how many records
there are in the DB at a given point of time). This means that to create
BaseTable table4, I need to know where table3 ends. That is why I am
using *float
table3y = table3.draw(); *and in the creation of table4 I sue table3y.

However, this is not working because table 3 went from page 1 to page 2. If
you notice, I have a sytem.out.println(table3y). This is returning 700.6
but it seems the system thinks it is still on page 1 but it has to be page
2!

Is the problem clear? How can I solve this problem?

Thanks in advance!

On Thu, Jun 2, 2016 at 8:46 PM, Erick Pezoa <erickpezoa@gmail.com> wrote:

> I am having another big issue that I hope you guys can help me with. I
> need to solve it because I need to deliver to a client.
>
> I will be sending in an hour or so the code and sample pdf to demonstrate
> the problem.
>
> Regards,
>
> Erick Pezoa.
>
> On Jun 2, 2016, at 2:44 PM, Dries Horions <notifications@github.com>
> wrote:
>
> Closed #62 <https://github.com/dhorions/boxable/issues/62>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhorions/boxable/issues/62#event-680224475>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGLFsdigL-L7e4W8_T1nyQBuK-n6Y1Wsks5qHySMgaJpZM4IpfSC>
> .
>
>


-- 
Regards,

Erick Pezoa.

**Comment by dobluth** [comment]
Hi Erick,

I did not look into your code, but you can use `Table.getCurrentPage()` to retrieve the page. Hope this already helps.

Markus

**Comment by Frulenzo** [comment]
Something like : 
```java
// did we change the page?
if (table.getCurrentPage() != page) {
    cos.close();
    page = table.getCurrentPage();
    cos = new PDPageContentStream(document, page, true, true);
}
```

where `page` is your current document page

**Comment by ErickPezoa** [comment]
Thanks guys. I thought with what you guys gave me I was going to be able to
fix the problem but it is not working yet. I added the below piece of code
so not sure why does it keep doing the same thing. Sorry to keep bothering
you!


[image: Inline image 1]

On Fri, Jun 3, 2016 at 3:02 AM, Hrvoje Štimac <notifications@github.com>
wrote:

> Something like :
>
> // did we change the page?if (table.getCurrentPage() != page) {
>     cos.close();
>     page = table.getCurrentPage();
>     cos = new PDPageContentStream(document, page, true, true);
> }
>
> where page is your current document page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhorions/boxable/issues/62#issuecomment-223505973>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGLFsZyiotQFtoW61Bv9RaUjcjl2Zy9-ks5qH9GegaJpZM4IpfSC>
> .
>



-- 
Regards,

Erick Pezoa.

**Comment by Frulenzo** [comment]
@ErickPezoa 
Can you provide some PDF outputs of this problem?

**Comment by ErickPezoa** [comment]
You can find it attached. It is still the same problem as before.

On Fri, Jun 3, 2016 at 7:40 AM, Hrvoje Štimac <notifications@github.com>
wrote:

> @ErickPezoa <https://github.com/ErickPezoa>
> Can you provide some PDF outputs of this problem?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhorions/boxable/issues/62#issuecomment-223557497>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGLFsfLVjyG8QXm0Z3cQtriilWVWIq_Tks5qIBKfgaJpZM4IpfSC>
> .
>



-- 
Regards,

Erick Pezoa.

**Comment by Frulenzo** [comment]
Unfortunately I don't see anything. I see only `[image: Inline image 1]` but that doesn't help much.

**Comment by ErickPezoa** [comment]
That is strange that you can't see the pdf. I am attaching three JPGs
showing the three difference pages. On the first page, you can see the
problem. (The table with title *Declaraciones y Autorizaciones*) should not
be on page1 but it should be on page 2.

On Fri, Jun 3, 2016 at 7:44 AM, Hrvoje Štimac <notifications@github.com>
wrote:

> Unfortunately I don't see anything. I see only [image: Inline image 1]
> but that doesn't help much.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhorions/boxable/issues/62#issuecomment-223558241>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGLFsaaUoTIQTtwK58jcBhbRMfFSBx6tks5qIBO6gaJpZM4IpfSC>
> .
>



-- 
Regards,

Erick Pezoa.

**Comment by Frulenzo** [comment]
Can you add please your PDF/JPGs over github.com and not over mail?

**Comment by ErickPezoa** [comment]
Done. I added the issue  #65.

https://github.com/dhorions/boxable/issues/65

On Fri, Jun 3, 2016 at 7:54 AM, Hrvoje Štimac <notifications@github.com>
wrote:

> Can you add please your PDF/JPGs over github.com and not over mail?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhorions/boxable/issues/62#issuecomment-223559933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGLFsdxs5dbroPKAcD5HWZpvxInzRWKWks5qIBYMgaJpZM4IpfSC>
> .
>



-- 
Regards,

Erick Pezoa.
