### ISSUE TITLE
Support page clipping

### ISSUE THREAD

**Issue by ammulder** [dhorions/boxable#63]
I have a designated area for a table, but I'm not in full control of the amount of data going into that space.  I'd like to set a clip rect on the page, so that if there's a bit more data than fits into the area, it will be clipped rather than overflowing the designated space.

I believe I need to set the clip rect in the content stream that the table is being rendered into (e.g. stream.addRect + stream.clip).  If that's correct, then either boxable needs to provide an option to give it a clip rect, or (I think) the method to create the stream needs to be not private so I can override it and set the clip rect when the stream is created.

For the same reason, I would like to be able to force it to never create a new page.  In my case that's not really a danger (the table area is high on the page and there's never THAT much too much data), but if I could I'd set the flag anyway to be sure.

**Comment by ammulder** [comment]
Well, maybe I was mistaken.  Looks like I can set the clip rect in a stream before the table stream, and then reset it in a stream after the table stream.  So I guess I can work around this.

**Comment by dhorions** [comment]
Glad it was resolved.
