### ISSUE TITLE
table is not recognizing that it should be added to a new page

### ISSUE THREAD

**Issue by ErickPezoa** [dhorions/boxable#65]
I have the attached code and the attached PDF (In case you can't open PDF, I am also attaching three JPGs). The relevant piece of code is also below. Notice what the problem is: table5 should be added to the next page but it is been added to the first one even though I am using `table.getCurrentPage() ` What am I missing here?

[PDFService.txt](https://github.com/dhorions/boxable/files/297501/PDFService.txt)
[samplePdf.pdf](https://github.com/dhorions/boxable/files/297504/samplePdf.pdf)
![page1](https://cloud.githubusercontent.com/assets/6473137/15777994/55c20340-2961-11e6-93b1-c5ec51767afa.jpg)
![page2](https://cloud.githubusercontent.com/assets/6473137/15777992/55c0d9f2-2961-11e6-9ce4-88a1ac285412.jpg)
![page3](https://cloud.githubusercontent.com/assets/6473137/15777993/55c1bf34-2961-11e6-85bb-0088736af7cd.jpg)

```
         /*
			 * checking to see if the table went to the other page
			 */
			if (table.getCurrentPage() != page) {
				contentStream.close();

				page = table.getCurrentPage();

				contentStream = new PDPageContentStream(document, page, true,
						true, true);
			}

			// creating fourth table Declaraciones y Autorizaciones

			BaseTable table5 = new BaseTable(table4y, 750, bottomMargin,
					tableWidth, margin, document, page, true, drawContent);

			// Create Header row
			row = table5.createRow(12f);
			cell = row.createCell(100, "Declaraciones y Autorizaciones",
					HorizontalAlignment.CENTER, VerticalAlignment.MIDDLE);
			cell.setFont(PDType1Font.HELVETICA_BOLD);
			cell.setFillColor(new Color(26, 82, 118));
			cell.setTextColor(Color.WHITE);

			table5.addHeaderRow(row);
```

**Comment by Frulenzo** [comment]
Can you add this part : 

```java
if (table.getCurrentPage() != page) {
    cos.close();
    page = table.getCurrentPage();
    cos = new PDPageContentStream(pageLayout.getDocument(), page, true, true);
}
```
After each `table.draw()`?

**Comment by dhorions** [comment]
Shouldn't you use table4 when getting the current page, instead of table?
not 
if (table.getCurrentPage() != page)
but
if ( table**4**.getCurrentPage() != page)

```
float table4y = table4.draw();

			// end table 4

			/*
			 * checking to see if the table went to the other page
			 */
			if (table.getCurrentPage() != page) {
				contentStream.close();

				page = table.getCurrentPage();

				contentStream = new PDPageContentStream(document, page, true,
						true, true);
			}
```

**Comment by dhorions** [comment]
@Frulenzo  if it's unsure what table it is, it should probably be checked for all 4 of them. If any table ended on a different page, that table should be the start.

**Comment by ErickPezoa** [comment]
Excellent! I didn't notice that mistake. I was using table instead of the respective table (In this case, table4). It works now! Thank you all!
