### ISSUE TITLE
Maven build doesn't pass (due javadoc)

### ISSUE THREAD

**Issue by Frulenzo** [dhorions/boxable#67]
So ```mvn package``` gives me this

[maven-build.pdf](https://github.com/dhorions/boxable/files/331197/maven-build.pdf)

It's just some javadoc but this also needs to be fixed.

**Comment by dhorions** [comment]
I see all these issues as warnings, and was able to release [1.5-RC.](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=com.github.dhorions&a=boxable&v=1.5-RC&e=jar&c=sources)
Was releasing version 1.5 what you were trying to do?  
Fixing those javadoc issues is definately nice, but not sure if absolutely required.

**Comment by Frulenzo** [comment]
If everything were just a warning and you manage to release 1.5-RC then it's great. I will still try to fix those javadoc issues to have more _clean_ maven build.

And kudos to you for new release!

**Comment by Frulenzo** [comment]
Just quick update. 
Last status: **17 errors, 94 warnings**
Current status said: **61 warnings**

Hopefully that would be submitted as PR in few days.

**Comment by Frulenzo** [comment]
Merged
