### ISSUE TITLE
Empty Cells fail to draw

### ISSUE THREAD

**Issue by vkuehn** [dhorions/boxable#68]
Hello,

not sure if it is right here. I am using boxable 1.4 with PDFBox 2.0.2 and I can create a Table with that

	public static BaseTable getTableFromListString(BaseTable tTable, List<String[]> cellText, PDFont font) {

		for (String[] vd : cellText) {
			Row<PDPage> row = tTable.createRow(HIGHT);
			Cell<PDPage> c = row.createCell(WIDTH1, vd[0]);
			c.setFont(font);
			c.setFillColor(Color.LIGHT_GRAY);
			c = row.createCell(WIDTH2, vd[1]);
			c = row.createCell(WIDTH3, vd[2]);
		}

		return tTable;
	}

But than Bastable draw fails when e.g. cell three is an empty string. This is because it has no hight.
See Table.class

	private boolean isEndOfPage(Row<T> row) {
		**float currentY = yStart - row.getHeight();**
		boolean isEndOfPage = currentY <= pageBottomMargin;
		if (isEndOfPage) {
			setTableIsBroken(true);
		}

		// If we are closer than bottom margin, consider this as
		// the end of the currentPage
		// If you add rows that are higher then bottom margin, this needs to be
		// checked
		// manually using getNextYPos
		return isEndOfPage;
	}

I think this worked in older versions

**Comment by Frulenzo** [comment]
Hmm that's awkward because if your cell is empty her's height would be calculated from maximal cell(s) height in the row. Even if your all cells are empty you will still get this particular row because minimal cell height is :

Cell Class ->  getCellHeight() method 

```java
[...]
return getTextHeight() +  getTopPadding() + getBottomPadding()
					+ (getTopBorder() == null ? 0 : getTopBorder().getWidth())
					+ (getBottomBorder() == null ? 0 : getBottomBorder().getWidth());
[...]
```
So if your getTextHeight() is 0 (empty cell) you should get minimal cell height from paddings and borders width.

Can you provide more info on debugging this particular method?

**Comment by vkuehn** [comment]
That error actually happend in your be.quodlibet.boxable.Table-> draw() so there is not much I can do if e.g for a table creation where I have empty cells in a row. Sorry if that was not clear

**Comment by Frulenzo** [comment]
I tried to recreate your problem with this test case (1 row, three cells, 1 cell is empty)

```java
@Test
    public void SampleTest7() throws IOException
    {

        //Set margins
        float margin = 10;

        //Initialize Document
        PDDocument doc = new PDDocument();
        PDPage page = addNewPage(doc);

        //Initialize table
        float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
        float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
        boolean drawContent = true;
        boolean drawLines = true;
        float yStart = yStartNewPage;
        float bottomMargin = 70;
        BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, drawLines,
                                        drawContent);

        //Create Header row
        Row<PDPage> row = table.createRow(0f);
        Cell<PDPage> cell = row.createCell((100 / 3f), "Hey I am not empty", HorizontalAlignment.get("center"),
                                           VerticalAlignment.get("top"));
        cell.setFontSize(6);

        Cell<PDPage> cell2 = row.createCell((100 / 3f), "", HorizontalAlignment.get("center"),
                                            VerticalAlignment.get("middle"));
        cell2.setFontSize(6);

        Cell<PDPage> cell3 = row.createCell((100 / 3f), "Hey I am not empty", HorizontalAlignment.get("center"),
                                            VerticalAlignment.get("bottom"));
        cell3.setFontSize(6);

        table.draw();

        //Save the document
        File file = new File("target/BoxableSample7.pdf");
        System.out.println("Sample file saved at : " + file.getAbsolutePath());
        Files.createParentDirs(file);
        doc.save(file);
        doc.close();
    }
```

My output:
[oneEmptyCell.pdf](https://github.com/dhorions/boxable/files/337035/oneEmptyCell.pdf)

If I misunderstood something can you remodify this test case to your actually state?

**Comment by vkuehn** [comment]
FYI I was able to reduce the problem to a strange character which caused a font error.
 Failed to create PDocumentU+FFFD ('.notdef') is not available in this font's encoding: WinAnsiEncoding
after a failed string operation Row<PDPage> accepted createlCell but failed in BaseTable.draw()

**Comment by Frulenzo** [comment]
Do you have something like this in your text cells ?
[unicode-charachter]( https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29#/media/File:Replacement_character.svg)


It's always a little bit problematic with encoding and fonts. If you want quick fix you can do something like:

```java
cellText = cellText.replace("\uFFFD", "");
```
To clean your current text from _breaking unicode_

**Comment by vkuehn** [comment]
Yes that was the case. Actually I have that now for my string operations. So thanks a lot ! 
But you might want to have it in you create cell method as a draw will always fail with such a letter

**Comment by Frulenzo** [comment]
That is unfortunately encoding problem. Even I fix that for you, it will definetly happen again. Font **Helvetica** doesn't support all unicode charachters

**Comment by vkuehn** [comment]
thanks, so I think we can close the issue.
Thanks a lot for your efforts here !

**Comment by Frulenzo** [comment]
I'm glad that we resolve encoding mystery :wink:
