### ISSUE TITLE
Rotate text in a cell

### ISSUE THREAD

**Issue by wermerb** [dhorions/boxable#7]
Hi!

I really love your work, it really makes our life easier to use PDFBox.
Is there any solution regarding to rotate a String in cell  ex. 90 degree?

Thanks in advanced.

**Comment by dhorions** [comment]
There is not at this time.  I don't have time to implement it myself, but if anyone wants to, it would be a good feature to add.

**Comment by Frulenzo** [comment]
I am just making that right now. Hopefully it will be done these days.

**Comment by dobluth** [comment]
See PR #19.

**Comment by wermerb** [comment]
Thank you so much :+1:.
I saw that it has been merged when will be tagged to 1.2.3?

**Comment by dhorions** [comment]
Version (1.3)[https://github.com/dhorions/boxable/releases] is released and resolves these issues.
