### ISSUE TITLE
How to detect if a row is the last row that fits on a page?

### ISSUE THREAD

**Issue by kazimiru** [dhorions/boxable#70]
Guys, please help me understand how pagination works in boxable(1.5-RC).

Scenario:

I'm generation a report which has two tables of the same structure but with different data set.
Second table should start from new page. To remove duplicated values from 1st column I 
simulate merging(it is not yet implemented as I understood) by changing bottom border style and values.

The problem:
First cell in last row on page has no bottom border. 

I tried to check if current row I'm filling at given loop iteration is the last on page. But I had no chance to 
find how to check this. I've found that PageProvider has curentPageIndex property but when I checked 
it in debug -- it's value is always -1 even when table already jumped on new page...

Can someone explain what is the correct way of handling pages?

Thanks beforehand!

**Comment by dhorions** [comment]
Hello,

could you provide us with a code sample and perhaps a sample of your output?  I don't really understand what you are trying to accomplish.

I'm assuming that by "merging" you mean that when multiple rows have the same content in the same column, you don't display the bottom border for those cells and don't repeat the values.
Is that correct?
How does this relate to handling pages?

> by changing bottom border style and values.

> The problem:
> First cell in last row on page has no bottom border.

Is it possible that you don't see a border *because* you changed the style so it's invisible?

**Comment by kazimiru** [comment]
>I'm assuming that by "merging" you mean that when multiple rows have the same content in the >same column, you don't display the bottom border for those cells and don't repeat the values.
>Is that correct?
>How does this relate to handling pages?

Yes. That's it. 
But the table can have lots of data and this happens -- it creates new page. So if column of "merged"
cells continues on next page -- previous page will have one cell without bottom border. 

> Is it possible that you don't see a border because you changed the style so it's invisible?

Yep that is exactly what I do and what I have.

So the task is to merge cells in 1st column. To do this I check the value for first cell an if it's the same as in row above -- I set empty value and remove border by setting it's color to white instead of black.

as a result I have pretty what I need except for the last row.
here is pic(sorry I can't show all table as data quite confidential :) ) 
https://sc-cdn.scaleengine.net/i/d0bed3dbe6b0d023c4797a16a0a3afcd.png 

Now I want to check if row that i'm working on now is the last on page so I can skip step of changing border color.

**Comment by dobluth** [comment]
Hi,

I see you are simulating a colspan behaviour. Right out of the head I would suggest the following:

Keep track of you current y position you would have, if the table would be drawn in the moment, while you are just constructing it. It starts at the `yStart` value you provide (`currentY = yStart`) and each row takes `row.getHeight()` space (`currentY -= row.getHeight()`). If this is lower than the remaining space, you will have a page break (`currentY <= pageBottomMargin`). In that case, you have to reset your `currentY` to the start position on the new page. Be aware, that on the next page all header rows will be drawn again.

Maybe there is another way, but I do not have more time at the moment.

Please let me know if you have any questions.

**Comment by kazimiru** [comment]
@dobluth, that did the trick for now. thanks a lot.
can you what are the plans on colspan\rowspan feature?

**Comment by dobluth** [comment]
Great!

I guess you are referencing #39. As you certainly have already read there, colspan is already possible. However, there are several problems regarding rowspan. Besides the borders you have to handle page breaks and (vertical) alignment. I do not know, when this feature will be implemented, sorry.

As your original problem is solved, I will close this issue.
