### ISSUE TITLE
Setting cell width as ratio of page width

### ISSUE THREAD

**Issue by lchis** [dhorions/boxable#72]
I'm having some trouble figuring out how to set cell widths so that they fit snug in the table.

I'm creating the table by setting the width as I've seen in the examples:
`float margin=10;
float tableWidth=page.getMediaBox().getWidth() - (2 * margin);`

I then create cells by setting their widths as a fraction of the tableWidth. I will have 13 cells, the first of which has to be 3 times wider than all the rest, so I am setting:

`Cell<PDPage> cell = row.createCell(3*tableWidth/15f, value);`

This gives me an error, saying 

> Cell Width=700.92804 can't be bigger than row width=592.0

My page's width is 612, so the tableWidth gets calculated correctly. Not sure why it thinks I'm trying to create massive cells though.

**Comment by dobluth** [comment]
Hi Ichis,

usually the cell widths are interpreted as fraction of the table width, so it should not be necessary to multiply by the table width. Please try the following expression:
```java
Cell<PDPage> cell = row.createCell(3/15f, value);
```

Hope this helps.

**Comment by Frulenzo** [comment]
As @dobluth said, creating cells is always created as % of the table width. It was poorly documented in previous versions but it's fixed now.

```java
@Test
	public void Test() throws IOException {

		//Set margins
		float margin = 10;

		//Initialize Document
		PDDocument doc = new PDDocument();
		PDPage page = addNewPage(doc);

		//Initialize table
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		boolean drawContent = true;
		boolean drawLines = true;
		float yStart = yStartNewPage;
		float bottomMargin = 70;
		BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, drawLines,
				drawContent);

		// set default line spacing for entire table
		table.setLineSpacing(1.5f);
		
		Row<PDPage> row = table.createRow(10);
		
		// set single spacing for entire row
		row.setLineSpacing(1f);

		// my first 3x wider cell
		Cell<PDPage> cell = row.createCell((3*100/15), "1",
				HorizontalAlignment.get("center"), VerticalAlignment.get("top"));
		cell.setFontSize(6);

                // my other 12 equal cells
		for(int i=2; i<14; i++){
			Cell<PDPage> cell2 = row.createCell((100/15f), String.valueOf(i),
					HorizontalAlignment.get("center"), VerticalAlignment.get("top"));
			cell2.setFontSize(6);
		}
		
		table.draw();

		//Save the document
		File file = new File("target/test.pdf");
		System.out.println("Sample file saved at : " + file.getAbsolutePath());
		Files.createParentDirs(file);
		doc.save(file);
		doc.close();
	}
```
PDF output
[13cells.pdf](https://github.com/dhorions/boxable/files/426444/13cells.pdf)

**Comment by lchis** [comment]
You guys rock, thanks for the quick response!

You were saying this was poorly documented in the past. Is there documentation that's now created?

**Comment by Frulenzo** [comment]
If you meant javadoc than yeah, it's slightly better documented now, particulary this method for creating cells but sadly it is not 100% documented (still working on that).
Other documentation you can find in our readme.md or here: [http://dhorions.github.io/boxable/](http://dhorions.github.io/boxable/)

**Comment by Frulenzo** [comment]
Closing the issue
