### ISSUE TITLE
Unable to draw the '<' character in a cell.

### ISSUE THREAD

**Issue by AUno-Antonison** [dhorions/boxable#74]
I am currently attempting to draw the '<' character within a cell but it appears to be blank.  I think it may have issues since this is also the beginning of a HTML tag, so maybe it removes it?

For now, I can only take a screenshots of the code/issue.  When I have time later today, I plan on creating a new project/sample code to test this out specifically.  
<img width="806" alt="screen shot 2016-09-11 at 6 33 06 am" src="https://cloud.githubusercontent.com/assets/18122185/18416972/cb0d0f4c-77e9-11e6-8cf4-0bde64c7cae1.png">

<img width="419" alt="screen shot 2016-09-11 at 6 11 57 am" src="https://cloud.githubusercontent.com/assets/18122185/18416872/c978dede-77e6-11e6-8d8e-1a0bf6ab603a.png">

**Comment by Frulenzo** [comment]
So when you can, please provide code snippet or PDF ouput because here is my fast test case :

```java
//Set margins
		float margin = 10;

		//Initialize Document
		PDDocument doc = new PDDocument();
		PDPage page = addNewPage(doc);

		//Initialize table
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		boolean drawContent = true;
		boolean drawLines = true;
		float yStart = yStartNewPage;
		float bottomMargin = 70;
		BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, drawLines,
				drawContent);

		//Create Header row
		Row<PDPage> row = table.createRow(15f);
		Cell<PDPage> cell = row.createCell(100f, "I want this < charachter is that okay? Maybe even this > also.", HorizontalAlignment.get("center"),
				VerticalAlignment.get("top"));
		cell.setFontSize(6);

		table.draw();

		//Save the document
		File file = new File("target/BoxableSample5.pdf");
		System.out.println("Sample file saved at : " + file.getAbsolutePath());
		Files.createParentDirs(file);
		doc.save(file);
		doc.close();
```
PDF output
[lessThan.pdf](https://github.com/dhorions/boxable/files/466646/lessThan.pdf)

**Comment by AUno-Antonison** [comment]
I went ahead and created some sample main methods and the pdfs generated to recreate it.  I didn't catch the extra note you added! 

**Regular Table**
`
      

        //Set margins
        float margin = 10;

        //Initialize Document
        PDDocument doc = new PDDocument();
        PDPage page = new PDPage();
        doc.addPage(page);

        //Initialize table
        float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
        float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
        boolean drawContent = true;
        boolean drawLines = true;
        float yStart = yStartNewPage;
        float bottomMargin = 70;
        BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, drawLines,
                drawContent);

        //Create Header row
        Row<PDPage> row = table.createRow(15f);
        Cell<PDPage> cell = row.createCell(40f, "I want this < charachter is that okay? Maybe even this > also.", HorizontalAlignment.get("center"),
                VerticalAlignment.get("top"));
        cell = row.createCell(20f, " | ");
        cell = row.createCell(40f, "right comparison");

        table.addHeaderRow(row);

        Row<PDPage> subtractionRow = table.createRow(15f);
        cell = subtractionRow.createCell(40f, "Removed Text From Document", HorizontalAlignment.get("center"),
                VerticalAlignment.get("top"));
        cell = subtractionRow.createCell(20f, " < ");
        cell = subtractionRow.createCell(40f, "text here");

        Row<PDPage> additionArow = table.createRow(15f);
        cell = additionArow.createCell(40f, "no empty cells", HorizontalAlignment.get("center"),
                VerticalAlignment.get("top"));
        cell = additionArow.createCell(20f, " > ");
        cell = additionArow.createCell(40f, "Added Text From Document");

        cell.setFontSize(6);

        table.draw();

        //Save the document
        File file = new File("BoxableSample5.pdf");
        System.out.println("Sample file saved at : " + file.getAbsolutePath());
        Files.createParentDirs(file);
        doc.save(file);
        doc.close();
    }
}`

**Data Table**

`
    public static void main(String[] args) throws IOException, ParseException {

        List<List> table = new ArrayList<>() ;

        List<String> tableHeader = new ArrayList<>();
        tableHeader.add("Left Comparison");
        tableHeader.add("  ");
        tableHeader.add("Right Comparison");

        table.add(tableHeader);

        List<String> additionRow = new ArrayList<>();
        additionRow.add("");
        additionRow.add(">");
        additionRow.add("Added Text To Document");
        table.add(additionRow);

        List<String> subtractionRow = new ArrayList<>();
        subtractionRow.add("Removed Text From Document");
        subtractionRow.add(" < ");
        subtractionRow.add("center row just has < in it");
        table.add(subtractionRow);

        List<String> updateRow = new ArrayList<>();
        updateRow.add("Original Text From Document");
        updateRow.add(" | ");
        updateRow.add("Changed Text From Document");
        table.add(updateRow);

        int startNewPageY = 700;
        int bottomMargin = 100;
        int tableWidth = 500;
        int leftMargin = 25;

        PDDocument document = new PDDocument();
        PDPage currentPage = new PDPage();
        document.addPage(currentPage);
        PDPageContentStream contentStream = new PDPageContentStream(document, currentPage);

        BaseTable dataTable = new BaseTable(700, startNewPageY, bottomMargin, tableWidth, leftMargin,
                document, currentPage, true, true);
        DataTable t = new DataTable(dataTable, currentPage);
        t.addListToTable(table, DataTable.HASHEADER);
        dataTable.draw();

        contentStream.close();

        try {
            document.save("test-less-than.pdf");
        } finally {
            document.close();
        }
    }


}`
[BoxableSample5.pdf](https://github.com/dhorions/boxable/files/467279/BoxableSample5.pdf)
[test-less-than.pdf](https://github.com/dhorions/boxable/files/467280/test-less-than.pdf)

**Comment by Frulenzo** [comment]
Yeah, I see that `<` is eaten but that is due this bug in Tokenizer. That would be fixed and merged in very close future (probably tomorrow).

**Comment by AUno-Antonison** [comment]
You are amazing!  Thank you for looking into it so fast.  

This library has been an absolute life saver.
