### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by jneuendorf** [dhorions/boxable#77]
Hi,

I'm currently working on a new feature in my fork.
What I need for another project is merging non-empty and empty cells (in the same row) automatically when using `DataTable`s to achieve something like this:

<img width="219" alt="want" src="https://cloud.githubusercontent.com/assets/6906734/19048131/5332996a-89a5-11e6-88a3-4fd28b11f46d.png">

instead of this:

<img width="297" alt="got" src="https://cloud.githubusercontent.com/assets/6906734/19048138/5c9d5152-89a5-11e6-9b9a-281aca004411.png">

But I'm not that familiar with building Java with Maven or Gradle (and the according configuration).
So my question is: **How can I run the project's test?**
I am using IntelliJ IDEA and it seems you're using Eclipse but I guess the workflow/configuration is the almost the same. So how have you setup your IDE in order to run your tests?

Thanks in advance! :)

**Comment by Frulenzo** [comment]
You can simple run them in `TableTest` class as simple JUnit tests. If you are not familiar with Maven or Gradle, I'm strongly suggesting to read their formal documentation and start to using them. Here is for example how to start with the Gradle in your IntelliJ IDE : [https://www.jetbrains.com/help/idea/2016.2/getting-started-with-gradle.html](url). Remember, official documentation is the best, if you have question then sprint to stackoverlow, if there you can't find the asnwer of your question or is specific boxable related then dropp your question here and someone will surely answer it :+1: 

Secondly, I didn't understand where is your problem. What you really want is second row with colspan = 3. We don't have perfect implemention of the colspan but you can always create second row with % value of your table and mimic the colspan.

Here is my test case for what you want: [https://gist.github.com/Frulenzo/a1c09843d5f0b5aae1e0cf5cdffa237d](url)

Test output
[sampleTest9.pdf](https://github.com/dhorions/boxable/files/507906/sampleTest9.pdf)

**Comment by jneuendorf** [comment]
Thanks for your reply. I will look into testing with `JUnit` later since I don't have so much time researching more stuff right now.
For that reason your little colspan example is even more helpful! I guess, I'll use your pattern of manually creating the colspan for now.

The idea of my fork was generating the colspan automatically (depending on the given data) because I like how easy using `DataTable`s is. :)

**Comment by Frulenzo** [comment]
I'm glad that this quick example helped you :)
