### ISSUE TITLE
Incorrect cell text left align

### ISSUE THREAD

**Issue by yuricrimtan** [dhorions/boxable#8]
Class: Table
Function: private void drawCellContent(Row row) throws IOException {

Code part: 
 while (cellIterator.hasNext()) {
.....
 nextX += cell.getWidth() + HorizontalCellMargin;
}

Remove: + HorizontalCellMargin;

In other case your cell text items will be moved right in case you have a lot of columns

**Comment by dhorions** [comment]
There was a reason this was there, although I don't remember exactly what it was.  If you make changes to this, make sure to do some testing to prevent possible side effects.

**Comment by Kravs** [comment]
I faced this issue also, in example codes.
Will take a look today.

**Comment by jsilverio** [comment]
That's exactly what I did also to solve this issue and I have not seen any side effects with it.

**Comment by jsilverio** [comment]
Excellent code by the way dhorions. You save me a lot of time.

**Comment by VJNarsi** [comment]
Thanks for the package. It made life easier. Could you please let me know if there is a plan to address this issue?

**Comment by dobluth** [comment]
The current code does not contain the ```HorizontalCellMargin``` anymore. Hopefully, your issues are already solved.

**Comment by leisamartella** [comment]
Do you have a timeframe for when your next release will be?

**Comment by Frulenzo** [comment]
@leisamartella for what exactly did you mean? If you meant for this issue, it's already solved in current stage (like dobluth said) or you had something else on your mind?

**Comment by leisamartella** [comment]
Thank you for your prompt reply.

The issue is that we would like to fix the alignment issue. But since there has been no official release for PDFBox 2.0 or Boxable, we did not want to take the risk of updating everything. It is our company’s policy to only update released products, so I was wondering if you had a timeframe that you have the next release of Boxable. We are using Boxable 1.2

Thanks!

**Comment by Konstantin-Skachkov** [comment]
How can I get a version with this fix in sbt?
Currently I have this:
libraryDependencies += "com.github.dhorions" % "boxable" % "1.2"

**Comment by dhorions** [comment]
Hello,

this is now resolved.  
Two new versions were released 
[1.2.1](https://github.com/dhorions/boxable/releases/tag/1.2.1) - Contains the latest code from master branch, and is references Pdfbox 2.0.0-RC**1**
[1.2.2](https://github.com/dhorions/boxable/releases/tag/1.2.2)  - Contains the latest code from master branch, and is references Pdfbox 2.0.0-RC**3**

**Comment by leisamartella** [comment]
Thank you!
