### ISSUE TITLE
Cells with many Rows of Text mess up the Order of the Text

### ISSUE THREAD

**Issue by gregorriegler** [dhorions/boxable#80]
`Iterator i$1 = cell.getParagraph().getMapLineTokens().entrySet().iterator();`
This is probably because the cell content gets split into a set whereas a Set has no guaranteed order.

**Comment by gregorriegler** [comment]
i think
https://github.com/dhorions/boxable/commit/29d73812478b6bea59f3a24e33e18ddc3b554e87
fixes it already

**Comment by Frulenzo** [comment]
You are correct and I close this isuse.
