### ISSUE TITLE
Error when trying to write multilines in cell

### ISSUE THREAD

**Issue by Puchin** [dhorions/boxable#82]
Hi, 

I started boxable 2 weeks ago and it's really useful. However, I'm facing some difficulties with cells positioning : 
- is it possible to have cells in a column, in a single row (like something as follows (dots are not visible. It's one big cell)) ?
 \___________________
\|.......................|______|
\|____________|______|

- trying to bypass the previous difficulty, I tried having my texts in multilines, by adding the character '\n' to my strings when creating my cells. However, doing so gives me the following error :
> Caused by: java.lang.IllegalArgumentException: U+000A ('controlLF') is not available in this font's encoding: WinAnsiEncoding

Is there any way for what I am trying to do ?

**Comment by Frulenzo** [comment]
Hi @Puchin,
Yeah, `\n` will not get you very far :smile:  If you want your texts in multiple lines can you use some of the HTML tags (<br>, <p>)? That's first thing that comes to my mind.

**Comment by Puchin** [comment]
Hi !
Thanks for your answer. It does work (didn't know I could put html tags ^^) !
However, it triggers something else : the wrapping is "broken" (at the end of the cell, the string just continues out of the cell while it didn't when not using <br>). How to keep the previous wrapping behaviour ?
I could use <p> tag though.

**Comment by Frulenzo** [comment]
Could you provide test case or some PDF output?

**Comment by Puchin** [comment]
I did something like this :
`Cell<PDPage> cell = row.createCell(75.0f, "Some text <br />" + "some long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long text">`

The long text will not go to a new line when reaching the right border of the cell (while it does if not using the `<br />` tag).

And is it possible to do the cells' separation I showed in my first post ? Because even if I can do multiple lines with html tags, it does not allow me to have different fonts in one cell, right ?

**Comment by Frulenzo** [comment]
Here is my test PDF
[longText.pdf](https://github.com/dhorions/boxable/files/599741/longText.pdf)

First cell ist `<br />` tag and the other is normal pure text without tags. I'm still not sure what is wrong with first cell? Isn't that what you want? After `Some text` just jump to new line?

For the second question, check out #62 clossed issue. I think that you ask same thing. As @dobluth said:

> I see three options to generate an output like in your image:
> 1. A table within a table (not possible with Boxable)
> 2. rowspan (not (yet) possible with Boxable, see #39)
> **3. try to fake a rowspan ;)**
> 
> To fake such a table you would have to generate 3 rows ("Grupo Familiar", "Adicionales", "Costo Total"). In the columns "Plan seleccionado" and "Código de Plan" you draw no borders between rows 1/2 and rows 2/3. It gets harder if you have some text in those two columns, as there are still three rows, leading to the question: where do you output it? But as long as there is no text, you should be fine ;)

And you asked: 

> it does not allow me to have different fonts in one cell, right ?

That's right. You can't have multiple fonts in one cell. You can have multiple fonts in a table though.

**Comment by Puchin** [comment]
Oooh thanks, it's working ! :D
Actually, there was a variable : `"text" + variable + "<br />" + "long long ... long text". `
Because of that, the long text would just get out of the cell.
But I tried adding a space before my tag : `" <br />"` and it's working now :)
Weird behaviour though... :p

**Comment by Frulenzo** [comment]
I saw your response in email but not here :confused:  Maybe you deleted your reply but to answer your question. I run the test also with no spaces between HTML tag and your other text and all seems fine.

**Comment by Puchin** [comment]
Yeah sorry, I was testing on the wrong part of the code, that's why my comment was not correct.
This is what I get with `<br />` tag :
[long_text](https://postimg.org/image/xg4dk6s9r/)

**Comment by Frulenzo** [comment]
I really want to replicate your scenario. Can you please provide me test case? If you don't want to write it all from scratch please simply copy one of the `TableTest` test cases and modify it.

Here, I give you mine:
``` java
@Test
	public void SampleTest7() throws IOException {

		// Set margins
		float margin = 10;

		// Initialize Document
		PDDocument doc = new PDDocument();
		PDPage page = addNewPage(doc);

		// Initialize table
		float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
		float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
		boolean drawContent = true;
		boolean drawLines = true;
		float yStart = yStartNewPage;
		float bottomMargin = 70;
		BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, drawLines,
				drawContent);

		// Create Header row
		Row<PDPage> row = table.createRow(15f);
		Cell<PDPage> cell = row.createCell(75.0f, "Some text<br />some long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long text");
		Row<PDPage> row2 = table.createRow(15f);
		Cell<PDPage> cell2 = row2.createCell(75.0f, "Some text some long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long text");
		table.draw();

		// Save the document
		File file = new File("target/BoxableSample7.pdf");
		System.out.println("Sample file saved at : " + file.getAbsolutePath());
		Files.createParentDirs(file);
		doc.save(file);
		doc.close();
	}
```
PDF output is already up.

**Comment by Puchin** [comment]
I took your code to put it in my function (just changed the part with the page). "outputSream" is used for a Response I return as RESTEasy service instead of saving in a file (this will be downloaded by my browser though).

```
            // Document creation
            PDDocument document = new PDDocument();
            document.addPage(new PDPage());
            PDPage page = document.getPage(0);

            // Initialize table
            float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
            float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
            boolean drawContent = true;
            boolean drawLines = true;
            float yStart = yStartNewPage;
            float bottomMargin = 70;
            BaseTable table = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, document, page,
                    drawLines, drawContent);

            // Create Header row
            Row<PDPage> row = table.createRow(15f);
            Cell<PDPage> cell = row.createCell(75.0f,
                    "Some text<br />some long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long text");
            Row<PDPage> row2 = table.createRow(15f);
            Cell<PDPage> cell2 = row2.createCell(75.0f,
                    "Some text some long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long text");
            table.draw();

            document.save(outputStream);
            document.close();
```

And here is the result :
[long_text](https://postimg.org/image/lttopz49f/)
