### ISSUE TITLE
Not able to write content using PDPageContentStream while drawing BaseTable

### ISSUE THREAD

**Issue by davdavarshal** [dhorions/boxable#83]
I am not able to write content using PDPageContentStream after drawing BaseTable on the same page.

I have also posted the same issue @apache pdfbox jira.
Link is here : https://issues.apache.org/jira/browse/PDFBOX-3580

**Comment by Frulenzo** [comment]
Is this already solved? I ask because I saw your last reply in that thread

**Comment by davdavarshal** [comment]
Hi
Yeah got solved yesterday.
