### ISSUE TITLE
Is there an available JAR file to use with Java 1.6?

### ISSUE THREAD

**Issue by howardtlcc** [dhorions/boxable#86]
I would like to use Boxable in a Java 1.6 environment. When I call:

 BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, pdfDoc, newPage, true, true);

I get an error.
Exception Thrown
javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=be/quodlibet/boxable/BaseTable, offset=6

I downloaded 1.3, 1.4, and 1.5 from Maven Central and all have the same issue. Is there a jar available that would work with Java 6?

thanks,

**Comment by Frulenzo** [comment]
Boxable doesn't have compiler compliance for 1.6
