### ISSUE TITLE
Braking long words

### ISSUE THREAD

**Issue by Kravs** [dhorions/boxable#9]
If you have really long word (e.g. 30 characters) and that word has width bigger than cell width, second part of this word should be forced to appear in next cell.

I will take a look into this if there would be no volunteers.

**Comment by dhorions** [comment]
That would be great, I don't have the time to look into it myself at this time.

**Comment by jsilverio** [comment]
![image](https://cloud.githubusercontent.com/assets/7980327/9452786/19767e50-4a6b-11e5-9244-e9f68dd44951.png)

Screenshot has the text wrapping not just using word split but by char. Tested this with thousands of records. Below are the changes I had made for the above.

(1) Row.java getHeight()

    public float getHeight() {

        float maxheight = new Float(0);

        
        for (Cell cell : this.cells) {
            int numLines = cell.getParagraph().getLines().size();
            float cellHeight = this.height;
            //J.S 8/24/15 Fixed excessive vertical spacing specially when cell content text wraps
            //cellHeight = (cell.getParagraph().getLines().size() * this.height);
            //cellHeight = this.height;
            cellHeight = cellHeight + (numLines > 1 ? new Double((numLines-1) * this.height * .65).floatValue() : 0);

            if (cellHeight > maxheight){
                maxheight = cellHeight;
            }
        }
        return maxheight;
    }

(2) Paragraph getLines()

    public List<String> getLines() {
        List<String> result = new ArrayList();

        String[] split = text.split("(?<=[\\W_-__])");

        int[] possibleWrapPoints = new int[split.length];

        possibleWrapPoints[0] = split[0].length();

        for (int i = 1; i < split.length; i++) {
            possibleWrapPoints[i] = possibleWrapPoints[i - 1] + split[i].length();
        }
        
        int start = 0;
        int end = 0;

        for (int i=1; i < text.length(); i++) {
            float width = 0;
            try {
                width = font.getStringWidth(text.substring(start, i)) / 1000 * fontSize;
            } catch (IOException e) {
                throw new IllegalArgumentException(e.getMessage(), e);
            }
            if (start < end && width > (this.width-5)) {
                result.add(text.substring(start, end));
                start = end;
            }
            end = i;
        }
        
        // Last piece of text
        result.add(text.substring(start));
        return result;
    }

**Comment by Kravs** [comment]
@jsilverio  thank you!
I will try you solution, and let you know :)

**Comment by jsilverio** [comment]
@Kravs I have a code that wraps by word like the original code and but also wraps by length for long words if that is what you need.

**Comment by Kravs** [comment]
@jsilverio I have the same feature implemented, but I wasn't here for long time, so I'm not sure if boxable has this feature in the latest release?

**Comment by dobluth** [comment]
This feature is not implemented in boxable itself, but you can set a custom ```WrappingFunction```, like this:

```java
final Cell<T> cell = row.createCell(width, content);
cell.setWrappingFunction(new WrappingFunction() {
	@Override
	public String[] getLines(final String text) {
		// caution, contains black magic
		// ...
		// [insert voodoo here, accessing final variable cell]
		// ...
		
		return result;
	}
});
```

This way you should be able to implement the algorithm of @jsilverio.

**Comment by dhorions** [comment]
This is fixed now in the master branch.  Will be part of next released version.

**Comment by wuruoyun** [comment]
When will be the next release? I need this fix.
