### ISSUE TITLE
Text wrapping in the table generated by DataTable

### ISSUE THREAD

**Issue by davdavarshal** [dhorions/boxable#91]
Hi,

I am generating a table from a List<List> using DataTable, but one problem I am facing is that, text don't get wrapped according to cell width, if there is any whitespace or '.' detected, then only data gets wrapped inside the cell, but in other case, it don't get wrapped and data goes into other cell.

I am using only addListToTable() of DataTable to draw table.

Thanks

**Comment by Frulenzo** [comment]
Can you provide test case and according PDF output? It is always much easier to start with some quick example rather implementing test case myself.

**Comment by davdavarshal** [comment]
[textWrappingPDFDemo.pdf](https://github.com/dhorions/boxable/files/770174/textWrappingPDFDemo.pdf)
Hi

Here is the demo file.
This data inside the table are dummy but the format is the same.
The number of columns are same. There has been space between data in 2nd and 3rd column as in my real data.
There is a List<List> which holds data.
I am using standard method of DataTable - addListToTable() to add this list.

Please help

**Comment by Frulenzo** [comment]
I think it is version problem. @dhorions has updated to 1.4 (d7d96031f764f7323392e1279853bc9928cbc3e2) at **5 Apr 2016** and I implemented this feature 6 days later (804cff41cf184fd3fe8be456fdb0e30b546d04df) **12 Apr 2016**

Here is just quick example that your case works:

```java
@Test
     public void test2() throws IOException
     {

         //Initialize Document
         PDDocument doc = new PDDocument();
         PDPage page = new PDPage();
         //Create a landscape page
         page.setMediaBox(new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth()));
         doc.addPage(page);
         //Initialize table
         float margin = 10;
         float tableWidth = page.getMediaBox().getWidth() - (2 * margin);
         float yStartNewPage = page.getMediaBox().getHeight() - (2 * margin);
         float yStart = yStartNewPage;
         float bottomMargin = 0;

         List<List> data = new ArrayList();
         data.add(new ArrayList<>(
                        Arrays.asList("Column One", "Column Two", "Column Three", "Column Four", "Column Five")));
         for (int i = 1; i <= 100; i++) {
	           data.add(new ArrayList<>(
	                        Arrays.asList("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "Rbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd", "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")));
         } 
         BaseTable dataTable = new BaseTable(yStart, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, true, true);
	     DataTable t = new DataTable(dataTable, page);
	     t.addListToTable(data, DataTable.HASHEADER);
	     dataTable.draw();
	         
	     File file = new File("target/testing.pdf");
	     System.out.println("Sample file saved at : " + file.getAbsolutePath());
	     Files.createParentDirs(file);
	     doc.save(file);
	     doc.close();

     }
```

[testing.pdf](https://github.com/dhorions/boxable/files/773784/testing.pdf)

**Comment by davdavarshal** [comment]
@Frulenzo, I am using the same version.
boxable - 1.4 and downloaded this library from Maven repository, even though facing the problem.

**Comment by Frulenzo** [comment]
Maybe I wasn't clear, in 1.4 this feature is **not** implemented.

**Comment by davdavarshal** [comment]
@Frulenzo, the issue got resolved.
I changed the version to 1.5 and in that version I am facing this problem.
Thanks for your time and this feature.

**Comment by vikas-jagga** [comment]
![issue](https://user-images.githubusercontent.com/29004403/30806922-4d94d606-a215-11e7-8c64-62c305e94342.PNG)
@davdavarshal Facing same issue as you can see in attached snapshot I am using Boxable 1.4. How it got resolved?

**Comment by Frulenzo** [comment]
@vikas-jagga try to find commit after release-1.4. As I said earlier, that is <b>not</b> implemented in 1.4 version

**Comment by davdavarshal** [comment]
@Frulenzo  Exactly
@vikas-jagga  I updated Boxable jar file to 1.5 RC and it got resolved.

Thanks

**Comment by vikas-jagga** [comment]
@Frulenzo @davdavarshal Thank you. I too updated it to 1.5-RC and it got resolved. By when we can expect release-1.5?
