### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by meddd** [dhorions/boxable#92]
hi,
it is posibility to update depnedences. https://www.versioneye.com/java/com.github.dhorions:boxable/1.4

when i compile with compile 'com.github.dhorions:boxable:1.4' i have got 
Warning:WARNING: Dependency commons-logging:commons-logging:1.2 is ignored for debug as it may be conflicting with the internal version provided by Android.

**Comment by Frulenzo** [comment]
@meddd 
Check new version ;)
