### ISSUE TITLE
Will not work on GAE due to java.awt.Color

### ISSUE THREAD

**Issue by Radagan** [dhorions/boxable#95]
I tried using boxable for a Google App Engine application, but java.awt.Color is not white listed. PDFBox works, but sadly not boxable.

**Comment by Frulenzo** [comment]
Yeah, I see here the list of [whitelisted classes](https://cloud.google.com/appengine/docs/standard/java/jrewhitelist?csw=1).
iText had the same problem: [link](http://blog.rubypdf.com/2009/12/17/how-to-run-itext-on-google-app-engine/). I found also this on [google groups](https://issuetracker.google.com/issues/35884388). When I find a little bit time I will look into it.
