### ISSUE TITLE
BaseTable.getLayouters() is not a method

### ISSUE THREAD

**Issue by cadaniel** [dhorions/boxable#97]
I'm trying to follow along the wiki for the styling of a table. I've tried both version 1.4 and 1.5-RC and neither show this as a method.

```
BaseTable table = new BaseTable(yPosition, yStartNewPage, bottomMargin, tableWidth, margin, doc, page, false, drawContent);

...

table.getLayouters().clear();
table.getLayouters().add(new DefaultCellLayouter(Styles.GREEN));
table.getLayouters().add(new ZebraCellLayouter(Styles.GREEN));
```

**Comment by Frulenzo** [comment]
Hmm, you are right. I thought that was already implemented by @dhorions. Maybe he can say more about that :smile:

**Comment by noamichael** [comment]
I'm also in need of this method! It would be very handy.

**Comment by avasekova** [comment]
The layouters, as shown on the wiki, seem to be implemented in the branch "api-SoC". They are not, however, included in the master and the latest release, so you won't see these methods if you just add boxable as a Maven dependency, for example.

**Comment by karimaelo** [comment]
We would like to use the layouters from the WIKI. It is not added in version 1.4. Could you please publish this change I really need it.

**Comment by Erwin-t-Hoen** [comment]
Would be great to be able to use the layouters.
